package internal

import (
	"crypto/rand"
	"log"
	"math/big"
)

var citiesMap = ClabeCities{
	{Code: 10, Name: "Aguascalientes", State: "MX-AGU"},
	{Code: 11, Name: "Asientos", State: "MX-AGU"},
	{Code: 12, Name: "Calvillo", State: "MX-AGU"},
	{Code: 13, Name: "Cosio", State: "MX-AGU"},
	{Code: 14, Name: "Jesús María", State: "MX-AGU"},
	{Code: 15, Name: "Pabellon de Arteaga", State: "MX-AGU"},
	{Code: 16, Name: "Rincon de Romos", State: "MX-AGU"},
	{Code: 17, Name: "San Fco Romo", State: "MX-AGU"},
	{Code: 20, Name: "Mexicali", State: "MX-BCN"},
	{Code: 21, Name: "Ciudad Morelos", State: "MX-BCN"},
	{Code: 22, Name: "Ensenada", State: "MX-BCN"},
	{Code: 23, Name: "Guadalupe Victoria", State: "MX-BCN"},
	{Code: 24, Name: "Rodolfo Sanchez T.", State: "MX-BCN"},
	{Code: 25, Name: "San Felipe", State: "MX-BCN"},
	{Code: 26, Name: "San Quintin", State: "MX-BCN"},
	{Code: 27, Name: "Tecate", State: "MX-BCN"},
	{Code: 28, Name: "Playas de Rosarito", State: "MX-BCN"},
	{Code: 40, Name: "La Paz", State: "MX-BCS"},
	{Code: 41, Name: "Cabo San Lucas", State: "MX-BCS"},
	{Code: 42, Name: "Ciudad Constitución", State: "MX-BCS"},
	{Code: 43, Name: "Guerrero Negro", State: "MX-BCS"},
	{Code: 44, Name: "Loreto", State: "MX-BCS"},
	{Code: 45, Name: "San José del Cabo", State: "MX-BCS"},
	{Code: 46, Name: "Santa Rosalía", State: "MX-BCS"},
	{Code: 47, Name: "Todos Santos", State: "MX-BCS"},
	{Code: 50, Name: "Campeche", State: "MX-CAM"},
	{Code: 51, Name: "Calkiní", State: "MX-CAM"},
	{Code: 52, Name: "Ciudad del Carmen", State: "MX-CAM"},
	{Code: 53, Name: "Champotón", State: "MX-CAM"},
	{Code: 54, Name: "Escarcega", State: "MX-CAM"},
	{Code: 55, Name: "Hopelchen", State: "MX-CAM"},
	{Code: 56, Name: "Palizada", State: "MX-CAM"},
	{Code: 57, Name: "Seybaplaya", State: "MX-CAM"},
	{Code: 60, Name: "Torreón", State: "MX-COA"},
	{Code: 61, Name: "Abasolo", State: "MX-COA"},
	{Code: 62, Name: "Acuña", State: "MX-COA"},
	{Code: 63, Name: "Allende", State: "MX-COA"},
	{Code: 64, Name: "Francisco I. Madero", State: "MX-COA"},
	{Code: 65, Name: "Frontera", State: "MX-COA"},
	{Code: 66, Name: "Laguna del Rey", State: "MX-COA"},
	{Code: 67, Name: "Matamoros", State: "MX-COA"},
	{Code: 68, Name: "Monclova", State: "MX-COA"},
	{Code: 69, Name: "Morelos", State: "MX-COA"},
	{Code: 70, Name: "Muzquiz", State: "MX-COA"},
	{Code: 71, Name: "Nava", State: "MX-COA"},
	{Code: 72, Name: "Nva Rosita", State: "MX-COA"},
	{Code: 73, Name: "Palau", State: "MX-COA"},
	{Code: 74, Name: "Parras de la Fuente", State: "MX-COA"},
	{Code: 75, Name: "Piedras Negras", State: "MX-COA"},
	{Code: 76, Name: "Ramos Arizpe", State: "MX-COA"},
	{Code: 77, Name: "Sabinas", State: "MX-COA"},
	{Code: 78, Name: "Saltillo", State: "MX-COA"},
	{Code: 79, Name: "San Buenaventura", State: "MX-COA"},
	{Code: 80, Name: "San Pedro de las Colonias", State: "MX-COA"},
	{Code: 81, Name: "Zaragoza", State: "MX-COA"},
	{Code: 90, Name: "Colima", State: "MX-COL"},
	{Code: 91, Name: "Armeria", State: "MX-COL"},
	{Code: 92, Name: "Comala", State: "MX-COL"},
	{Code: 93, Name: "Coquimatlan", State: "MX-COL"},
	{Code: 94, Name: "Cuauhtemoc", State: "MX-COL"},
	{Code: 95, Name: "Manzanillo", State: "MX-COL"},
	{Code: 96, Name: "Queseria", State: "MX-COL"},
	{Code: 97, Name: "Tecomán", State: "MX-COL"},
	{Code: 98, Name: "Villa de Alvarez", State: "MX-COL"},
	{Code: 100, Name: "Tuxtla Gutiérrez", State: "MX-CHP"},
	{Code: 101, Name: "Acapetahua", State: "MX-CHP"},
	{Code: 102, Name: "Angel Albino Corzo", State: "MX-CHP"},
	{Code: 103, Name: "Arriaga", State: "MX-CHP"},
	{Code: 104, Name: "Bochil", State: "MX-CHP"},
	{Code: 105, Name: "Cacahoatan", State: "MX-CHP"},
	{Code: 106, Name: "Catazaja", State: "MX-CHP"},
	{Code: 107, Name: "Cintalapa", State: "MX-CHP"},
	{Code: 108, Name: "Ciudad Hidalgo", State: "MX-CHP"},
	{Code: 109, Name: "Comitán de Dominguez", State: "MX-CHP"},
	{Code: 110, Name: "Copainala", State: "MX-CHP"},
	{Code: 111, Name: "Chiapa de Corso", State: "MX-CHP"},
	{Code: 112, Name: "Chicomuselo", State: "MX-CHP"},
	{Code: 113, Name: "Frontera Comalapa", State: "MX-CHP"},
	{Code: 114, Name: "Huixtla", State: "MX-CHP"},
	{Code: 115, Name: "Jiquipilas", State: "MX-CHP"},
	{Code: 116, Name: "Juarez", State: "MX-CHP"},
	{Code: 117, Name: "La Concordia", State: "MX-CHP"},
	{Code: 118, Name: "La Trinitaria", State: "MX-CHP"},
	{Code: 119, Name: "Las Margaritas", State: "MX-CHP"},
	{Code: 120, Name: "Las Rosas", State: "MX-CHP"},
	{Code: 121, Name: "Mapastepec", State: "MX-CHP"},
	{Code: 122, Name: "Motozintla", State: "MX-CHP"},
	{Code: 123, Name: "Ocosingo", State: "MX-CHP"},
	{Code: 124, Name: "Ocozocoautla", State: "MX-CHP"},
	{Code: 125, Name: "Palenque", State: "MX-CHP"},
	{Code: 126, Name: "Pichucalco", State: "MX-CHP"},
	{Code: 127, Name: "Pijijiapan", State: "MX-CHP"},
	{Code: 128, Name: "Reforma", State: "MX-CHP"},
	{Code: 129, Name: "Salto de Agua", State: "MX-CHP"},
	{Code: 130, Name: "San Cristóbal de las Casas", State: "MX-CHP"},
	{Code: 131, Name: "Simojovel", State: "MX-CHP"},
	{Code: 132, Name: "Socoltenango", State: "MX-CHP"},
	{Code: 133, Name: "Tapachula", State: "MX-CHP"},
	{Code: 134, Name: "Teopisca", State: "MX-CHP"},
	{Code: 135, Name: "Tonala", State: "MX-CHP"},
	{Code: 136, Name: "Tuxtla Chico", State: "MX-CHP"},
	{Code: 137, Name: "Venustiano Carranza", State: "MX-CHP"},
	{Code: 138, Name: "Villa Corzo", State: "MX-CHP"},
	{Code: 140, Name: "Yajalón", State: "MX-CHP"},
	{Code: 150, Name: "Chihuahua", State: "MX-CHH"},
	{Code: 151, Name: "Ahumada", State: "MX-CHH"},
	{Code: 152, Name: "Anahuac", State: "MX-CHH"},
	{Code: 153, Name: "Ascension", State: "MX-CHH"},
	{Code: 154, Name: "Buenaventura", State: "MX-CHH"},
	{Code: 155, Name: "Camargo", State: "MX-CHH"},
	{Code: 156, Name: "Casas Grandes", State: "MX-CHH"},
	{Code: 157, Name: "Creel", State: "MX-CHH"},
	{Code: 158, Name: "Cuauhtemoc", State: "MX-CHH"},
	{Code: 159, Name: "Gomez Farias", State: "MX-CHH"},
	{Code: 160, Name: "Guachochi", State: "MX-CHH"},
	{Code: 161, Name: "Guerrero", State: "MX-CHH"},
	{Code: 162, Name: "Hidalgo del Parral", State: "MX-CHH"},
	{Code: 163, Name: "Ciudad Jiménez", State: "MX-CHH"},
	{Code: 164, Name: "Ciudad Juárez", State: "MX-CHH"},
	{Code: 165, Name: "Madera", State: "MX-CHH"},
	{Code: 166, Name: "Meoqui", State: "MX-CHH"},
	{Code: 167, Name: "Nameiquipa", State: "MX-CHH"},
	{Code: 168, Name: "Nvo Casas Grandes", State: "MX-CHH"},
	{Code: 169, Name: "Ojinaga", State: "MX-CHH"},
	{Code: 170, Name: "Praxedis G. Guerrero", State: "MX-CHH"},
	{Code: 171, Name: "Puerto Palomas", State: "MX-CHH"},
	{Code: 172, Name: "Santa Barbara", State: "MX-CHH"},
	{Code: 173, Name: "Saucillo", State: "MX-CHH"},
	{Code: 180, Name: "Ciudad de México", State: "MX-CMX"},
	{Code: 190, Name: "Durango", State: "MX-DUR"},
	{Code: 191, Name: "Canatlan", State: "MX-DUR"},
	{Code: 192, Name: "Cuencame", State: "MX-DUR"},
	{Code: 193, Name: "El Salto", State: "MX-DUR"},
	{Code: 194, Name: "Guadalupe Victoria", State: "MX-DUR"},
	{Code: 195, Name: "Nazas", State: "MX-DUR"},
	{Code: 196, Name: "Nvo Ideal", State: "MX-DUR"},
	{Code: 197, Name: "San Juan del Rio", State: "MX-DUR"},
	{Code: 198, Name: "Santa Maria del Oro", State: "MX-DUR"},
	{Code: 199, Name: "Santiago Papasquiaro", State: "MX-DUR"},
	{Code: 200, Name: "Tayoltita", State: "MX-DUR"},
	{Code: 201, Name: "Tepehuanes", State: "MX-DUR"},
	{Code: 202, Name: "Vicente Guerrero", State: "MX-DUR"},
	{Code: 210, Name: "Guanajuato", State: "MX-GUA"},
	{Code: 211, Name: "Abasolo", State: "MX-GUA"},
	{Code: 212, Name: "Acámbaro", State: "MX-GUA"},
	{Code: 213, Name: "Apaseo el Alto", State: "MX-GUA"},
	{Code: 214, Name: "Apaseo el Grande", State: "MX-GUA"},
	{Code: 215, Name: "Celaya", State: "MX-GUA"},
	{Code: 216, Name: "Comonfort", State: "MX-GUA"},
	{Code: 217, Name: "Coroneo", State: "MX-GUA"},
	{Code: 218, Name: "Cortazar", State: "MX-GUA"},
	{Code: 219, Name: "Cuerámaro", State: "MX-GUA"},
	{Code: 220, Name: "Dolores Hidalgo", State: "MX-GUA"},
	{Code: 221, Name: "Huanimaro", State: "MX-GUA"},
	{Code: 222, Name: "Irapuato", State: "MX-GUA"},
	{Code: 223, Name: "Jaral del Progreso", State: "MX-GUA"},
	{Code: 224, Name: "Jerécuaro", State: "MX-GUA"},
	{Code: 225, Name: "León", State: "MX-GUA"},
	{Code: 226, Name: "Manuel Doblado", State: "MX-GUA"},
	{Code: 227, Name: "Moroleón", State: "MX-GUA"},
	{Code: 228, Name: "Ocampo", State: "MX-GUA"},
	{Code: 229, Name: "Pénjamo", State: "MX-GUA"},
	{Code: 230, Name: "Pueblo Nuevo", State: "MX-GUA"},
	{Code: 231, Name: "Purisima del Rincon", State: "MX-GUA"},
	{Code: 232, Name: "Romita", State: "MX-GUA"},
	{Code: 233, Name: "Salamanca", State: "MX-GUA"},
	{Code: 234, Name: "Salvatierra", State: "MX-GUA"},
	{Code: 235, Name: "San Diego de la Union", State: "MX-GUA"},
	{Code: 236, Name: "San Felipe Progreso", State: "MX-GUA"},
	{Code: 237, Name: "San Francisco del Rincoón", State: "MX-GUA"},
	{Code: 238, Name: "San José Iturbide", State: "MX-GUA"},
	{Code: 239, Name: "San Luis de la Paz", State: "MX-GUA"},
	{Code: 240, Name: "San Miguel de Allende", State: "MX-GUA"},
	{Code: 241, Name: "Santa Ana Pacueco", State: "MX-GUA"},
	{Code: 242, Name: "Santa Cruz de Juventino", State: "MX-GUA"},
	{Code: 243, Name: "Santiago Maravatio", State: "MX-GUA"},
	{Code: 244, Name: "Silao", State: "MX-GUA"},
	{Code: 245, Name: "Tarandacuao", State: "MX-GUA"},
	{Code: 246, Name: "Tarimoro", State: "MX-GUA"},
	{Code: 247, Name: "Uriangato", State: "MX-GUA"},
	{Code: 248, Name: "Valle de Santiago", State: "MX-GUA"},
	{Code: 249, Name: "Yuriria", State: "MX-GUA"},
	{Code: 260, Name: "Chilpancingo", State: "MX-GRO"},
	{Code: 261, Name: "Acapulco de Juarez", State: "MX-GRO"},
	{Code: 262, Name: "Apaxtla de Castrejon", State: "MX-GRO"},
	{Code: 263, Name: "Arcelia", State: "MX-GRO"},
	{Code: 264, Name: "Atoyac de Álvarez", State: "MX-GRO"},
	{Code: 265, Name: "Buenavista de Cuellar", State: "MX-GRO"},
	{Code: 266, Name: "Ciudad Altamirano", State: "MX-GRO"},
	{Code: 267, Name: "Coyuca de Benítez", State: "MX-GRO"},
	{Code: 268, Name: "Cruz Grande", State: "MX-GRO"},
	{Code: 269, Name: "Chichihualco", State: "MX-GRO"},
	{Code: 270, Name: "Chilapa de Alvarez", State: "MX-GRO"},
	{Code: 271, Name: "Huitzuco", State: "MX-GRO"},
	{Code: 272, Name: "Iguala", State: "MX-GRO"},
	{Code: 273, Name: "Olinala", State: "MX-GRO"},
	{Code: 274, Name: "Ometepec", State: "MX-GRO"},
	{Code: 275, Name: "San Marcos", State: "MX-GRO"},
	{Code: 276, Name: "Taxco de Alarcon", State: "MX-GRO"},
	{Code: 277, Name: "Petatlan", State: "MX-GRO"},
	{Code: 278, Name: "Teloloapan", State: "MX-GRO"},
	{Code: 279, Name: "Tierra Colorada", State: "MX-GRO"},
	{Code: 280, Name: "Tixtla de Guerrero", State: "MX-GRO"},
	{Code: 281, Name: "Tlapa de Comonfort", State: "MX-GRO"},
	{Code: 282, Name: "Ixtapa Zihuatanejo", State: "MX-GRO"},
	{Code: 290, Name: "Pachuca de Soto", State: "MX-HID"},
	{Code: 291, Name: "Actopan", State: "MX-HID"},
	{Code: 292, Name: "Apam", State: "MX-HID"},
	{Code: 293, Name: "Atotonilco el Grande", State: "MX-HID"},
	{Code: 294, Name: "Ciudad Sahagún", State: "MX-HID"},
	{Code: 295, Name: "Cuautepec de Hinojosa", State: "MX-HID"},
	{Code: 296, Name: "Huejutla de Reyes", State: "MX-HID"},
	{Code: 297, Name: "Huichapan", State: "MX-HID"},
	{Code: 298, Name: "Ixmiquilpan", State: "MX-HID"},
	{Code: 299, Name: "Jacala", State: "MX-HID"},
	{Code: 300, Name: "Metztitlan", State: "MX-HID"},
	{Code: 301, Name: "Mixquiahuala", State: "MX-HID"},
	{Code: 302, Name: "Molango", State: "MX-HID"},
	{Code: 303, Name: "Progreso de Obregón", State: "MX-HID"},
	{Code: 304, Name: "Tasquillo", State: "MX-HID"},
	{Code: 305, Name: "Tepeapulco", State: "MX-HID"},
	{Code: 306, Name: "Tepeji del Rio", State: "MX-HID"},
	{Code: 307, Name: "Tezontepec", State: "MX-HID"},
	{Code: 308, Name: "Tizayuca", State: "MX-HID"},
	{Code: 309, Name: "Tlahuelilpan", State: "MX-HID"},
	{Code: 310, Name: "Tlaxcoapan", State: "MX-HID"},
	{Code: 311, Name: "Tula de Allende", State: "MX-HID"},
	{Code: 312, Name: "Tulancingo", State: "MX-HID"},
	{Code: 313, Name: "Zacualtipán", State: "MX-HID"},
	{Code: 314, Name: "Zimapán", State: "MX-HID"},
	{Code: 320, Name: "El Salto", State: "MX-JAL"},
	{Code: 321, Name: "Acatic", State: "MX-JAL"},
	{Code: 322, Name: "Acatlan de Juarez", State: "MX-JAL"},
	{Code: 323, Name: "Ahualulco de Mercado", State: "MX-JAL"},
	{Code: 324, Name: "Ajijic", State: "MX-JAL"},
	{Code: 325, Name: "Amatitan", State: "MX-JAL"},
	{Code: 326, Name: "Ameca", State: "MX-JAL"},
	{Code: 327, Name: "Arandas", State: "MX-JAL"},
	{Code: 328, Name: "Arenal", State: "MX-JAL"},
	{Code: 329, Name: "Atenguillo", State: "MX-JAL"},
	{Code: 330, Name: "Atotonilco el Alto", State: "MX-JAL"},
	{Code: 331, Name: "Atotonilquillo", State: "MX-JAL"},
	{Code: 332, Name: "Atoyac", State: "MX-JAL"},
	{Code: 333, Name: "Autlán de Navarro", State: "MX-JAL"},
	{Code: 334, Name: "Ayotlan", State: "MX-JAL"},
	{Code: 335, Name: "Ayutla", State: "MX-JAL"},
	{Code: 336, Name: "Bajio de San Jose", State: "MX-JAL"},
	{Code: 337, Name: "Belen del Refugio", State: "MX-JAL"},
	{Code: 338, Name: "Cañadas de Obregon", State: "MX-JAL"},
	{Code: 339, Name: "Capilla de Guadalupe", State: "MX-JAL"},
	{Code: 340, Name: "Casimiro Castillo", State: "MX-JAL"},
	{Code: 341, Name: "Cihuatlán", State: "MX-JAL"},
	{Code: 342, Name: "Ciudad Guzmán", State: "MX-JAL"},
	{Code: 343, Name: "Cocula", State: "MX-JAL"},
	{Code: 344, Name: "Ixtlixochitl", State: "MX-MEX"},
	{Code: 345, Name: "Cuquio", State: "MX-JAL"},
	{Code: 346, Name: "Chapala", State: "MX-JAL"},
	{Code: 347, Name: "Degollado", State: "MX-JAL"},
	{Code: 348, Name: "El Grullo", State: "MX-JAL"},
	{Code: 349, Name: "Encarnacion de Diaz", State: "MX-JAL"},
	{Code: 350, Name: "Estipac", State: "MX-JAL"},
	{Code: 351, Name: "Guachinango", State: "MX-JAL"},
	{Code: 352, Name: "Huejucar", State: "MX-JAL"},
	{Code: 353, Name: "Huejuquilla el Alto", State: "MX-JAL"},
	{Code: 354, Name: "Ixtlahuacan de los M.", State: "MX-JAL"},
	{Code: 355, Name: "Ixtlahuacán del Río", State: "MX-JAL"},
	{Code: 356, Name: "Jalostotitlán", State: "MX-JAL"},
	{Code: 357, Name: "Jamay", State: "MX-JAL"},
	{Code: 358, Name: "Jesus Maria", State: "MX-JAL"},
	{Code: 359, Name: "Jocotepec", State: "MX-JAL"},
	{Code: 360, Name: "Juchitlan", State: "MX-JAL"},
	{Code: 361, Name: "La Barca", State: "MX-JAL"},
	{Code: 362, Name: "Lagos de Moreno", State: "MX-JAL"},
	{Code: 363, Name: "Magdalena", State: "MX-JAL"},
	{Code: 364, Name: "Manzanilla de la Paz", State: "MX-JAL"},
	{Code: 365, Name: "Mascota", State: "MX-JAL"},
	{Code: 366, Name: "Mazamitla", State: "MX-JAL"},
	{Code: 367, Name: "Mexticacan", State: "MX-JAL"},
	{Code: 368, Name: "Mezquitic", State: "MX-JAL"},
	{Code: 369, Name: "Mixtlan", State: "MX-JAL"},
	{Code: 370, Name: "Ocotlán", State: "MX-JAL"},
	{Code: 371, Name: "Ojuelos de Jalisco", State: "MX-JAL"},
	{Code: 372, Name: "Pegueros", State: "MX-JAL"},
	{Code: 373, Name: "Pihuamo", State: "MX-JAL"},
	{Code: 374, Name: "Poncitlan", State: "MX-JAL"},
	{Code: 375, Name: "Puerto Vallarta", State: "MX-JAL"},
	{Code: 376, Name: "Purificacion", State: "MX-JAL"},
	{Code: 377, Name: "Quitupan", State: "MX-JAL"},
	{Code: 378, Name: "San Ignacio Cerro G.", State: "MX-JAL"},
	{Code: 379, Name: "San Jose Casas Caidas", State: "MX-JAL"},
	{Code: 380, Name: "San Jose de Gracia", State: "MX-JAL"},
	{Code: 381, Name: "San Juan de los Lagos", State: "MX-JAL"},
	{Code: 382, Name: "San Julian", State: "MX-JAL"},
	{Code: 383, Name: "San Martin Hidalgo", State: "MX-JAL"},
	{Code: 384, Name: "San Miguel el Alto", State: "MX-JAL"},
	{Code: 385, Name: "San Patricio Melaque", State: "MX-JAL"},
	{Code: 386, Name: "Sayula", State: "MX-JAL"},
	{Code: 387, Name: "Tala", State: "MX-JAL"},
	{Code: 388, Name: "Talpa de Allende", State: "MX-JAL"},
	{Code: 389, Name: "Tamazula de Gordiano", State: "MX-JAL"},
	{Code: 390, Name: "Tapalpa", State: "MX-JAL"},
	{Code: 391, Name: "Tecalitlán", State: "MX-JAL"},
	{Code: 392, Name: "Tecolotlan", State: "MX-JAL"},
	{Code: 393, Name: "TeNameaxtlan", State: "MX-JAL"},
	{Code: 394, Name: "Teocaltiche", State: "MX-JAL"},
	{Code: 395, Name: "Teocuitatlan de Corona", State: "MX-JAL"},
	{Code: 396, Name: "Tepatitlán de Morelos", State: "MX-JAL"},
	{Code: 397, Name: "Tequila", State: "MX-JAL"},
	{Code: 398, Name: "Tizapan el Alto", State: "MX-JAL"},
	{Code: 399, Name: "Toliman", State: "MX-JAL"},
	{Code: 400, Name: "Tomatlan", State: "MX-JAL"},
	{Code: 401, Name: "Tonaya", State: "MX-JAL"},
	{Code: 402, Name: "Totatiche", State: "MX-JAL"},
	{Code: 403, Name: "Tototlán", State: "MX-JAL"},
	{Code: 404, Name: "Tuxpan", State: "MX-JAL"},
	{Code: 405, Name: "Union de San Antonio", State: "MX-JAL"},
	{Code: 406, Name: "Union de Tula", State: "MX-JAL"},
	{Code: 407, Name: "Valle de Guadalupe", State: "MX-JAL"},
	{Code: 408, Name: "Valle de Juarez", State: "MX-JAL"},
	{Code: 409, Name: "Villa Corona", State: "MX-JAL"},
	{Code: 410, Name: "Villa Guerrero", State: "MX-JAL"},
	{Code: 411, Name: "Villa Hidalgo", State: "MX-JAL"},
	{Code: 412, Name: "Vista Hermosa", State: "MX-JAL"},
	{Code: 413, Name: "Zacoalco de Torres", State: "MX-JAL"},
	{Code: 414, Name: "Zapotiltic", State: "MX-JAL"},
	{Code: 415, Name: "Zapotlan del Rey", State: "MX-JAL"},
	{Code: 416, Name: "Zapotlanejo", State: "MX-JAL"},
	{Code: 420, Name: "Toluca", State: "MX-MEX"},
	{Code: 421, Name: "Acambay", State: "MX-MEX"},
	{Code: 422, Name: "Almoloya de Juárez", State: "MX-MEX"},
	{Code: 423, Name: "Amatepec", State: "MX-MEX"},
	{Code: 424, Name: "Amecameca", State: "MX-MEX"},
	{Code: 425, Name: "Apaxco", State: "MX-MEX"},
	{Code: 426, Name: "Atlacomulco", State: "MX-MEX"},
	{Code: 427, Name: "Capulhuac", State: "MX-MEX"},
	{Code: 428, Name: "Coatepec de Harinas", State: "MX-MEX"},
	{Code: 429, Name: "Colorines", State: "MX-MEX"},
	{Code: 430, Name: "Chicoloapan", State: "MX-MEX"},
	{Code: 431, Name: "Chiconcuac", State: "MX-MEX"},
	{Code: 432, Name: "El Oro", State: "MX-MEX"},
	{Code: 433, Name: "Ixtapan de la Sal", State: "MX-MEX"},
	{Code: 434, Name: "Ixtlahuaca", State: "MX-MEX"},
	{Code: 435, Name: "Jilotepec", State: "MX-MEX"},
	{Code: 436, Name: "Jocotitlan", State: "MX-MEX"},
	{Code: 437, Name: "Chimalhuacan", State: "MX-MEX"},
	{Code: 438, Name: "Lerma", State: "MX-MEX"},
	{Code: 439, Name: "Luvianos", State: "MX-MEX"},
	{Code: 440, Name: "Malinalco", State: "MX-MEX"},
	{Code: 441, Name: "Metepec", State: "MX-MEX"},
	{Code: 442, Name: "Ocoyoacac", State: "MX-MEX"},
	{Code: 443, Name: "Otumba", State: "MX-MEX"},
	{Code: 444, Name: "San Felipe Progreso", State: "MX-MEX"},
	{Code: 445, Name: "San Mateo Atenco", State: "MX-MEX"},
	{Code: 446, Name: "Tejupilco", State: "MX-MEX"},
	{Code: 447, Name: "Temascalcingo", State: "MX-MEX"},
	{Code: 448, Name: "Temascaltepec", State: "MX-MEX"},
	{Code: 449, Name: "Temoaya", State: "MX-MEX"},
	{Code: 450, Name: "Tenancingo", State: "MX-MEX"},
	{Code: 451, Name: "Tenango de Arista", State: "MX-MEX"},
	{Code: 452, Name: "Texcaltitlan", State: "MX-MEX"},
	{Code: 453, Name: "Tianguistenco", State: "MX-MEX"},
	{Code: 454, Name: "Tonatico", State: "MX-MEX"},
	{Code: 455, Name: "Tultepec", State: "MX-MEX"},
	{Code: 456, Name: "Tultitlán", State: "MX-MEX"},
	{Code: 457, Name: "Valle de Bravo", State: "MX-MEX"},
	{Code: 458, Name: "Villa del Carbon", State: "MX-MEX"},
	{Code: 459, Name: "Villa Guerrero", State: "MX-MEX"},
	{Code: 460, Name: "Villa Nicolás Romero", State: "MX-MEX"},
	{Code: 461, Name: "Villa Victoria", State: "MX-MEX"},
	{Code: 462, Name: "Xonacatlan", State: "MX-MEX"},
	{Code: 463, Name: "Zumpango", State: "MX-MEX"},
	{Code: 470, Name: "Morelia", State: "MX-MIC"},
	{Code: 471, Name: "Acuitzio del Canje", State: "MX-MIC"},
	{Code: 472, Name: "Aguililla", State: "MX-MIC"},
	{Code: 473, Name: "Alvaro Obregon", State: "MX-MIC"},
	{Code: 474, Name: "Angamacutiro", State: "MX-MIC"},
	{Code: 475, Name: "Angangueo", State: "MX-MIC"},
	{Code: 476, Name: "Apatzingán", State: "MX-MIC"},
	{Code: 477, Name: "Ario de Rosales", State: "MX-MIC"},
	{Code: 478, Name: "Arteaga", State: "MX-MIC"},
	{Code: 479, Name: "Buenavista Tomatlan", State: "MX-MIC"},
	{Code: 480, Name: "Ciudad Hidalgo", State: "MX-MIC"},
	{Code: 481, Name: "Coalcoman de Vazquez", State: "MX-MIC"},
	{Code: 482, Name: "Contepec", State: "MX-MIC"},
	{Code: 483, Name: "Cotija de la Paz", State: "MX-MIC"},
	{Code: 484, Name: "Cuitzeo", State: "MX-MIC"},
	{Code: 485, Name: "Chavinda", State: "MX-MIC"},
	{Code: 486, Name: "Cheran", State: "MX-MIC"},
	{Code: 487, Name: "Chilchota", State: "MX-MIC"},
	{Code: 488, Name: "Churintzio", State: "MX-MIC"},
	{Code: 489, Name: "Epitacio Huerta", State: "MX-MIC"},
	{Code: 490, Name: "Gabriel Zamora", State: "MX-MIC"},
	{Code: 491, Name: "Huandacareo", State: "MX-MIC"},
	{Code: 492, Name: "Huetamo", State: "MX-MIC"},
	{Code: 493, Name: "Jacona de Plancarte", State: "MX-MIC"},
	{Code: 494, Name: "Jiquilpan de Juarez", State: "MX-MIC"},
	{Code: 495, Name: "La Huacana", State: "MX-MIC"},
	{Code: 496, Name: "La Piedad de Cabadas", State: "MX-MIC"},
	{Code: 497, Name: "Lázaro Cárdenas", State: "MX-MIC"},
	{Code: 498, Name: "Los Reyes de Salgado", State: "MX-MIC"},
	{Code: 499, Name: "Maravatío", State: "MX-MIC"},
	{Code: 500, Name: "San Jose de Gracia", State: "MX-MIC"},
	{Code: 501, Name: "Nva Italia de Ruiz", State: "MX-MIC"},
	{Code: 502, Name: "Pajacuaran", State: "MX-MIC"},
	{Code: 503, Name: "Panindicuaro", State: "MX-MIC"},
	{Code: 504, Name: "Paracho", State: "MX-MIC"},
	{Code: 505, Name: "Pastor Ortiz", State: "MX-MIC"},
	{Code: 506, Name: "Pátzcuaro", State: "MX-MIC"},
	{Code: 507, Name: "Periban", State: "MX-MIC"},
	{Code: 508, Name: "Purépero de Echaiz", State: "MX-MIC"},
	{Code: 509, Name: "Puruandiro", State: "MX-MIC"},
	{Code: 510, Name: "Querendaro", State: "MX-MIC"},
	{Code: 511, Name: "Quiroga", State: "MX-MIC"},
	{Code: 512, Name: "Sahuayo de Morelos", State: "MX-MIC"},
	{Code: 513, Name: "Santa Ana Maya", State: "MX-MIC"},
	{Code: 514, Name: "Santiago Tangamandapio", State: "MX-MIC"},
	{Code: 515, Name: "Tacámbaro Codallos", State: "MX-MIC"},
	{Code: 516, Name: "Tancitaro", State: "MX-MIC"},
	{Code: 517, Name: "Tangancícuaro Arista", State: "MX-MIC"},
	{Code: 518, Name: "Tanhuato de Guerrero", State: "MX-MIC"},
	{Code: 519, Name: "Tapalcatepec", State: "MX-MIC"},
	{Code: 520, Name: "Taretan", State: "MX-MIC"},
	{Code: 521, Name: "Tinguindin", State: "MX-MIC"},
	{Code: 522, Name: "Tlalpujahua", State: "MX-MIC"},
	{Code: 523, Name: "Tlazazalca", State: "MX-MIC"},
	{Code: 524, Name: "Tocumbo", State: "MX-MIC"},
	{Code: 525, Name: "Tuxpan", State: "MX-MIC"},
	{Code: 526, Name: "Tuzantla", State: "MX-MIC"},
	{Code: 527, Name: "Ucareo", State: "MX-MIC"},
	{Code: 528, Name: "Uruapan", State: "MX-MIC"},
	{Code: 529, Name: "Villa Jimenez", State: "MX-MIC"},
	{Code: 530, Name: "Villamar", State: "MX-MIC"},
	{Code: 531, Name: "Villa Morelos", State: "MX-MIC"},
	{Code: 532, Name: "Vista Hermosa Negrete", State: "MX-MIC"},
	{Code: 533, Name: "Yurécuaro", State: "MX-MIC"},
	{Code: 534, Name: "Zacapu", State: "MX-MIC"},
	{Code: 535, Name: "Zamora", State: "MX-MIC"},
	{Code: 536, Name: "Zinapécuaro", State: "MX-MIC"},
	{Code: 537, Name: "Zitácuaro", State: "MX-MIC"},
	{Code: 540, Name: "Cuernavaca", State: "MX-MOR"},
	{Code: 541, Name: "Axochiapan", State: "MX-MOR"},
	{Code: 542, Name: "Cuautla", State: "MX-MOR"},
	{Code: 543, Name: "Jiutepec", State: "MX-MOR"},
	{Code: 544, Name: "Jojutla", State: "MX-MOR"},
	{Code: 545, Name: "Puente de Ixtla", State: "MX-MOR"},
	{Code: 546, Name: "Temixco", State: "MX-MOR"},
	{Code: 547, Name: "Tepoztlan", State: "MX-MOR"},
	{Code: 548, Name: "Tetecala", State: "MX-MOR"},
	{Code: 549, Name: "Yautepec", State: "MX-MOR"},
	{Code: 551, Name: "Yecapixtla", State: "MX-MOR"},
	{Code: 552, Name: "Zacatepec", State: "MX-MOR"},
	{Code: 560, Name: "Tepic", State: "MX-NAY"},
	{Code: 561, Name: "Acaponeta", State: "MX-NAY"},
	{Code: 562, Name: "Ahuacatlán", State: "MX-NAY"},
	{Code: 563, Name: "Amatlan de Cañas", State: "MX-NAY"},
	{Code: 564, Name: "Compostela", State: "MX-NAY"},
	{Code: 565, Name: "Huajicori", State: "MX-NAY"},
	{Code: 566, Name: "Ixtlán del Río", State: "MX-NAY"},
	{Code: 567, Name: "La Penita de Jaltemba", State: "MX-NAY"},
	{Code: 568, Name: "Las Varas", State: "MX-NAY"},
	{Code: 569, Name: "Rosamorada", State: "MX-NAY"},
	{Code: 570, Name: "Ruiz", State: "MX-NAY"},
	{Code: 571, Name: "San Blas", State: "MX-NAY"},
	{Code: 572, Name: "Santa Maria del Oro", State: "MX-NAY"},
	{Code: 573, Name: "Santiago Ixcuintla", State: "MX-NAY"},
	{Code: 574, Name: "Tecuala", State: "MX-NAY"},
	{Code: 575, Name: "Túxpam", State: "MX-NAY"},
	{Code: 576, Name: "Villa Hidalgo", State: "MX-NAY"},
	{Code: 577, Name: "Xalisco", State: "MX-NAY"},
	{Code: 580, Name: "Apodaca", State: "MX-NLE"},
	{Code: 581, Name: "Abasolo", State: "MX-NLE"},
	{Code: 582, Name: "Agualeguas", State: "MX-NLE"},
	{Code: 583, Name: "Allende", State: "MX-NLE"},
	{Code: 584, Name: "Anahuac", State: "MX-NLE"},
	{Code: 585, Name: "Bustamante", State: "MX-NLE"},
	{Code: 586, Name: "Cerralvo", State: "MX-NLE"},
	{Code: 587, Name: "Cienega de Flores", State: "MX-NLE"},
	{Code: 588, Name: "China", State: "MX-NLE"},
	{Code: 589, Name: "Galeana", State: "MX-NLE"},
	{Code: 590, Name: "General Bravo", State: "MX-NLE"},
	{Code: 591, Name: "General Teran", State: "MX-NLE"},
	{Code: 592, Name: "General Zuazua", State: "MX-NLE"},
	{Code: 593, Name: "Hidalgo", State: "MX-NLE"},
	{Code: 594, Name: "Lampazos de Naranjo", State: "MX-NLE"},
	{Code: 595, Name: "Linares", State: "MX-NLE"},
	{Code: 596, Name: "Los Ramones", State: "MX-NLE"},
	{Code: 597, Name: "Montemorelos", State: "MX-NLE"},
	{Code: 598, Name: "Pesqueria", State: "MX-NLE"},
	{Code: 599, Name: "Sabinas Hidalgo", State: "MX-NLE"},
	{Code: 600, Name: "Salinas Victoria", State: "MX-NLE"},
	{Code: 601, Name: "Santiago", State: "MX-NLE"},
	{Code: 610, Name: "Oaxaca", State: "MX-OAX"},
	{Code: 611, Name: "Asuncion Nochixtlan", State: "MX-OAX"},
	{Code: 612, Name: "Guelatao", State: "MX-OAX"},
	{Code: 613, Name: "Heroica Cd de Tlaxiaco", State: "MX-OAX"},
	{Code: 614, Name: "Huajuapan de León", State: "MX-OAX"},
	{Code: 615, Name: "Huautla", State: "MX-OAX"},
	{Code: 616, Name: "Ixtepec", State: "MX-OAX"},
	{Code: 617, Name: "Juchitán de Zaragoza", State: "MX-OAX"},
	{Code: 618, Name: "La Reforma", State: "MX-OAX"},
	{Code: 619, Name: "Loma Bonita", State: "MX-OAX"},
	{Code: 620, Name: "Matías Romero", State: "MX-OAX"},
	{Code: 621, Name: "Miahuatlán", State: "MX-OAX"},
	{Code: 622, Name: "Ocotlán", State: "MX-OAX"},
	{Code: 623, Name: "Pinotepa", State: "MX-OAX"},
	{Code: 624, Name: "Puerto Escondido", State: "MX-OAX"},
	{Code: 625, Name: "Putla", State: "MX-OAX"},
	{Code: 626, Name: "Salina Cruz", State: "MX-OAX"},
	{Code: 627, Name: "San Andres Lagunas", State: "MX-OAX"},
	{Code: 628, Name: "San Juan Bautista T.", State: "MX-OAX"},
	{Code: 629, Name: "San Pedro Mixtepec", State: "MX-OAX"},
	{Code: 630, Name: "San Pedro Pochutla", State: "MX-OAX"},
	{Code: 631, Name: "San Pedro Tapanatepec", State: "MX-OAX"},
	{Code: 632, Name: "Santa Lucía del Camino", State: "MX-OAX"},
	{Code: 633, Name: "Santa Maria del Tule", State: "MX-OAX"},
	{Code: 634, Name: "Santa Maria Huatulco", State: "MX-OAX"},
	{Code: 635, Name: "Santiago Juxtlahuaca", State: "MX-OAX"},
	{Code: 636, Name: "Santiago Pinotepa Nal", State: "MX-OAX"},
	{Code: 637, Name: "Sto Domingo Tehuantepec", State: "MX-OAX"},
	{Code: 638, Name: "Tlacolula D Matamoros", State: "MX-OAX"},
	{Code: 639, Name: "Villa de Tamazulapam", State: "MX-OAX"},
	{Code: 640, Name: "Zimatlán", State: "MX-OAX"},
	{Code: 650, Name: "Cuautlancingo", State: "MX-PUE"},
	{Code: 651, Name: "Acatlan", State: "MX-PUE"},
	{Code: 652, Name: "Acatzingo", State: "MX-PUE"},
	{Code: 653, Name: "Amozoc", State: "MX-PUE"},
	{Code: 654, Name: "Atlixco", State: "MX-PUE"},
	{Code: 655, Name: "Ciudad Serdan", State: "MX-PUE"},
	{Code: 656, Name: "Cuetzalan", State: "MX-PUE"},
	{Code: 657, Name: "Chiautla", State: "MX-PUE"},
	{Code: 658, Name: "Chignahuapan", State: "MX-PUE"},
	{Code: 659, Name: "Huauchinango", State: "MX-PUE"},
	{Code: 660, Name: "Huejotzingo", State: "MX-PUE"},
	{Code: 661, Name: "Hueytamalco", State: "MX-PUE"},
	{Code: 662, Name: "Izúcar de Matamoros", State: "MX-PUE"},
	{Code: 663, Name: "Libres", State: "MX-PUE"},
	{Code: 664, Name: "Nealtican", State: "MX-PUE"},
	{Code: 665, Name: "Nvo Necaxa", State: "MX-PUE"},
	{Code: 666, Name: "Rafael Lara Grajales", State: "MX-PUE"},
	{Code: 667, Name: "San Martín Texmelucan", State: "MX-PUE"},
	{Code: 668, Name: "Sto Tomas Hueyotlipan", State: "MX-PUE"},
	{Code: 669, Name: "Tecamachalco", State: "MX-PUE"},
	{Code: 670, Name: "Tehuacán", State: "MX-PUE"},
	{Code: 671, Name: "Tepeaca", State: "MX-PUE"},
	{Code: 672, Name: "Teziutlán", State: "MX-PUE"},
	{Code: 673, Name: "Tlatlauquitepec", State: "MX-PUE"},
	{Code: 674, Name: "Xicotepec de Juárez", State: "MX-PUE"},
	{Code: 675, Name: "Zacapoaxtla", State: "MX-PUE"},
	{Code: 676, Name: "Zacatlán", State: "MX-PUE"},
	{Code: 680, Name: "El Pueblito Correg.", State: "MX-QUE"},
	{Code: 681, Name: "Amealco", State: "MX-QUE"},
	{Code: 682, Name: "Cadereyta", State: "MX-QUE"},
	{Code: 683, Name: "Ezequiel Montes", State: "MX-QUE"},
	{Code: 684, Name: "Jalpan", State: "MX-QUE"},
	{Code: 685, Name: "San Juan del Río", State: "MX-QUE"},
	{Code: 686, Name: "Tequisquiapan", State: "MX-QUE"},
	{Code: 690, Name: "Chetumal", State: "MX-ROO"},
	{Code: 691, Name: "Cancún", State: "MX-ROO"},
	{Code: 692, Name: "Cozumel", State: "MX-ROO"},
	{Code: 693, Name: "Isla Mujeres", State: "MX-ROO"},
	{Code: 694, Name: "Playa del Carmen", State: "MX-ROO"},
	{Code: 700, Name: "San Luis Potosí", State: "MX-SLP"},
	{Code: 701, Name: "Axtla de Terrazas", State: "MX-SLP"},
	{Code: 702, Name: "Cardenas", State: "MX-SLP"},
	{Code: 703, Name: "Cerritos", State: "MX-SLP"},
	{Code: 704, Name: "Ciudad del Maiz", State: "MX-SLP"},
	{Code: 705, Name: "Ciudad Valles", State: "MX-SLP"},
	{Code: 706, Name: "Charcas", State: "MX-SLP"},
	{Code: 707, Name: "Ebano", State: "MX-SLP"},
	{Code: 708, Name: "Guadalcazar", State: "MX-SLP"},
	{Code: 709, Name: "Matehuala", State: "MX-SLP"},
	{Code: 710, Name: "Rayon", State: "MX-SLP"},
	{Code: 711, Name: "Río Verde", State: "MX-SLP"},
	{Code: 712, Name: "Salinas de Hidalgo", State: "MX-SLP"},
	{Code: 713, Name: "Santa Maria del Rio", State: "MX-SLP"},
	{Code: 714, Name: "Tamasopo", State: "MX-SLP"},
	{Code: 715, Name: "Tamazunchale", State: "MX-SLP"},
	{Code: 716, Name: "Tamuín", State: "MX-SLP"},
	{Code: 717, Name: "Tancanhuitz de Santos", State: "MX-SLP"},
	{Code: 718, Name: "Tanquian", State: "MX-SLP"},
	{Code: 719, Name: "Tierra Nueva", State: "MX-SLP"},
	{Code: 720, Name: "Venado", State: "MX-SLP"},
	{Code: 721, Name: "Xilitla", State: "MX-SLP"},
	{Code: 722, Name: "Villa de Arista", State: "MX-SLP"},
	{Code: 730, Name: "Culiacán", State: "MX-SIN"},
	{Code: 731, Name: "Ahome", State: "MX-SIN"},
	{Code: 732, Name: "Angostura", State: "MX-SIN"},
	{Code: 733, Name: "Badiraguato", State: "MX-SIN"},
	{Code: 734, Name: "Bamoa", State: "MX-SIN"},
	{Code: 735, Name: "Concordia", State: "MX-SIN"},
	{Code: 736, Name: "Cosala", State: "MX-SIN"},
	{Code: 737, Name: "Choix", State: "MX-SIN"},
	{Code: 738, Name: "El Fuerte", State: "MX-SIN"},
	{Code: 739, Name: "Escuinapa de Hidalgo", State: "MX-SIN"},
	{Code: 740, Name: "Guamúchil", State: "MX-SIN"},
	{Code: 741, Name: "Guasave", State: "MX-SIN"},
	{Code: 742, Name: "La Cruz de Elota", State: "MX-SIN"},
	{Code: 743, Name: "Los Mochis", State: "MX-SIN"},
	{Code: 744, Name: "Mazatlán", State: "MX-SIN"},
	{Code: 745, Name: "Mocorito", State: "MX-SIN"},
	{Code: 746, Name: "Navolato", State: "MX-SIN"},
	{Code: 747, Name: "Quila", State: "MX-SIN"},
	{Code: 748, Name: "Rosario", State: "MX-SIN"},
	{Code: 749, Name: "San Blas", State: "MX-SIN"},
	{Code: 750, Name: "San Ignacio", State: "MX-SIN"},
	{Code: 760, Name: "Hermosillo", State: "MX-SON"},
	{Code: 761, Name: "Agua Prieta", State: "MX-SON"},
	{Code: 762, Name: "Alamos", State: "MX-SON"},
	{Code: 763, Name: "Altar", State: "MX-SON"},
	{Code: 764, Name: "Baviacora", State: "MX-SON"},
	{Code: 765, Name: "Caborca", State: "MX-SON"},
	{Code: 766, Name: "Cananea", State: "MX-SON"},
	{Code: 767, Name: "Ciudad Obregón", State: "MX-SON"},
	{Code: 768, Name: "Cumpas", State: "MX-SON"},
	{Code: 769, Name: "Empalme", State: "MX-SON"},
	{Code: 770, Name: "Guaymas", State: "MX-SON"},
	{Code: 771, Name: "Huatabampo", State: "MX-SON"},
	{Code: 772, Name: "Luis B. Sanchez", State: "MX-SON"},
	{Code: 773, Name: "Magdalena de Kino", State: "MX-SON"},
	{Code: 774, Name: "Miguel Aleman", State: "MX-SON"},
	{Code: 775, Name: "Moctezuma", State: "MX-SON"},
	{Code: 776, Name: "Nacozari de García", State: "MX-SON"},
	{Code: 777, Name: "Navojoa", State: "MX-SON"},
	{Code: 778, Name: "Nogales", State: "MX-SON"},
	{Code: 779, Name: "Puerto Peñasco", State: "MX-SON"},
	{Code: 780, Name: "San Luis Río Colorado", State: "MX-SON"},
	{Code: 781, Name: "Santa Ana", State: "MX-SON"},
	{Code: 782, Name: "Ures", State: "MX-SON"},
	{Code: 783, Name: "Villa Juarez (Irrigacion)", State: "MX-SON"},
	{Code: 790, Name: "Villa Hermosa", State: "MX-TAB"},
	{Code: 791, Name: "Balancan", State: "MX-TAB"},
	{Code: 792, Name: "Cardenas", State: "MX-TAB"},
	{Code: 793, Name: "Ciudad Pemex", State: "MX-TAB"},
	{Code: 794, Name: "Comalcalco", State: "MX-TAB"},
	{Code: 795, Name: "Cunduacan", State: "MX-TAB"},
	{Code: 796, Name: "Emiliano Zapata", State: "MX-TAB"},
	{Code: 797, Name: "Frontera", State: "MX-TAB"},
	{Code: 798, Name: "Huimanguillo", State: "MX-TAB"},
	{Code: 799, Name: "Jalapa", State: "MX-TAB"},
	{Code: 800, Name: "Jalpa de Méndez", State: "MX-TAB"},
	{Code: 801, Name: "Jonuta", State: "MX-TAB"},
	{Code: 802, Name: "Macuspana", State: "MX-TAB"},
	{Code: 803, Name: "Nacajuca", State: "MX-TAB"},
	{Code: 804, Name: "Paraíso", State: "MX-TAB"},
	{Code: 805, Name: "Tacotalpa", State: "MX-TAB"},
	{Code: 806, Name: "Teapa", State: "MX-TAB"},
	{Code: 807, Name: "Tenosique", State: "MX-TAB"},
	{Code: 810, Name: "Ciudad Victoria", State: "MX-TAM"},
	{Code: 811, Name: "Altamira", State: "MX-TAM"},
	{Code: 812, Name: "Camargo", State: "MX-TAM"},
	{Code: 813, Name: "Ciudad Madero", State: "MX-TAM"},
	{Code: 814, Name: "Ciudad Mante", State: "MX-TAM"},
	{Code: 815, Name: "Ciudad Miguel Aleman", State: "MX-TAM"},
	{Code: 816, Name: "Gonzalez", State: "MX-TAM"},
	{Code: 817, Name: "Gustavo Diaz Ordaz", State: "MX-TAM"},
	{Code: 818, Name: "Matamoros", State: "MX-TAM"},
	{Code: 819, Name: "Mier", State: "MX-TAM"},
	{Code: 820, Name: "Nva Ciudad Guerrero", State: "MX-TAM"},
	{Code: 821, Name: "Nuevo Laredo", State: "MX-TAM"},
	{Code: 822, Name: "Hidalgo", State: "MX-TAM"},
	{Code: 823, Name: "Río Bravo", State: "MX-TAM"},
	{Code: 824, Name: "San Fernando", State: "MX-TAM"},
	{Code: 825, Name: "Soto la Marina", State: "MX-TAM"},
	{Code: 826, Name: "Valle Hermoso", State: "MX-TAM"},
	{Code: 827, Name: "Xicotencatl", State: "MX-TAM"},
	{Code: 830, Name: "Tlaxcala", State: "MX-TLA"},
	{Code: 831, Name: "Amaxac de Guerrero", State: "MX-TLA"},
	{Code: 832, Name: "Apizaco", State: "MX-TLA"},
	{Code: 833, Name: "Calpulalpan", State: "MX-TLA"},
	{Code: 834, Name: "Chiautempan", State: "MX-TLA"},
	{Code: 835, Name: "Huamantla", State: "MX-TLA"},
	{Code: 836, Name: "Papalotla", State: "MX-TLA"},
	{Code: 837, Name: "Santa Maria Nativitas", State: "MX-TLA"},
	{Code: 838, Name: "Tlaxco", State: "MX-TLA"},
	{Code: 839, Name: "Zacatelco", State: "MX-TLA"},
	{Code: 840, Name: "Xalapa", State: "MX-VER"},
	{Code: 841, Name: "Acayucan", State: "MX-VER"},
	{Code: 842, Name: "Adalberto Tejeda", State: "MX-VER"},
	{Code: 843, Name: "Agua Dulce", State: "MX-VER"},
	{Code: 844, Name: "Agua Dulce (Papantla)", State: "MX-VER"},
	{Code: 845, Name: "Álamo", State: "MX-VER"},
	{Code: 846, Name: "Altotonga", State: "MX-VER"},
	{Code: 847, Name: "Alvarado", State: "MX-VER"},
	{Code: 848, Name: "Banderilla", State: "MX-VER"},
	{Code: 849, Name: "Boca del Río", State: "MX-VER"},
	{Code: 850, Name: "Catemaco", State: "MX-VER"},
	{Code: 851, Name: "Cerro Azul", State: "MX-VER"},
	{Code: 852, Name: "Ciudad Mendoza", State: "MX-VER"},
	{Code: 853, Name: "Coatepec", State: "MX-VER"},
	{Code: 854, Name: "Coatzacoalcos", State: "MX-VER"},
	{Code: 855, Name: "Córdoba", State: "MX-VER"},
	{Code: 856, Name: "Cosamaloapan", State: "MX-VER"},
	{Code: 858, Name: "Coscomatepec", State: "MX-VER"},
	{Code: 859, Name: "Cosoleacaque", State: "MX-VER"},
	{Code: 860, Name: "Cuitláhuac", State: "MX-VER"},
	{Code: 861, Name: "Chicontepec", State: "MX-VER"},
	{Code: 862, Name: "El Naranjal", State: "MX-VER"},
	{Code: 863, Name: "Fortín de las Flores", State: "MX-VER"},
	{Code: 864, Name: "Gutiérrez Zamora", State: "MX-VER"},
	{Code: 865, Name: "Huatusco", State: "MX-VER"},
	{Code: 866, Name: "Hueyapan de Ocampo", State: "MX-VER"},
	{Code: 867, Name: "Isla", State: "MX-VER"},
	{Code: 868, Name: "Ixtaczoquitlán", State: "MX-VER"},
	{Code: 869, Name: "Jáltipan de Morelos", State: "MX-VER"},
	{Code: 870, Name: "Jesus Carranza", State: "MX-VER"},
	{Code: 871, Name: "Juan Rodríguez Clara", State: "MX-VER"},
	{Code: 872, Name: "La Antigua", State: "MX-VER"},
	{Code: 873, Name: "Las Choapas", State: "MX-VER"},
	{Code: 874, Name: "Lerdo de Tejada", State: "MX-VER"},
	{Code: 875, Name: "Los Naranjos", State: "MX-VER"},
	{Code: 876, Name: "Martínez de la Torre", State: "MX-VER"},
	{Code: 877, Name: "Minatitlán", State: "MX-VER"},
	{Code: 878, Name: "Misantla", State: "MX-VER"},
	{Code: 879, Name: "Nanchital", State: "MX-VER"},
	{Code: 880, Name: "Naolinco", State: "MX-VER"},
	{Code: 881, Name: "Naranjos", State: "MX-VER"},
	{Code: 882, Name: "Orizaba", State: "MX-VER"},
	{Code: 883, Name: "Ozuluama", State: "MX-VER"},
	{Code: 884, Name: "Panuco", State: "MX-VER"},
	{Code: 885, Name: "Papantla", State: "MX-VER"},
	{Code: 886, Name: "Perote", State: "MX-VER"},
	{Code: 887, Name: "Playa Vicente", State: "MX-VER"},
	{Code: 888, Name: "Poza Rica", State: "MX-VER"},
	{Code: 889, Name: "Río Blanco", State: "MX-VER"},
	{Code: 890, Name: "San Andrés Tuxtla", State: "MX-VER"},
	{Code: 891, Name: "San Rafael", State: "MX-VER"},
	{Code: 892, Name: "Soledad de Doblado", State: "MX-VER"},
	{Code: 893, Name: "Tamiahua", State: "MX-VER"},
	{Code: 894, Name: "Tantoyuca", State: "MX-VER"},
	{Code: 895, Name: "Tempoal de Sanchez", State: "MX-VER"},
	{Code: 896, Name: "Teocelo", State: "MX-VER"},
	{Code: 897, Name: "Tezonapa", State: "MX-VER"},
	{Code: 898, Name: "Tierra Blanca", State: "MX-VER"},
	{Code: 899, Name: "Tihuatlan", State: "MX-VER"},
	{Code: 900, Name: "Tlacotalpan", State: "MX-VER"},
	{Code: 901, Name: "Tlapacoyan", State: "MX-VER"},
	{Code: 902, Name: "Tres Valles", State: "MX-VER"},
	{Code: 903, Name: "Tuxpan", State: "MX-VER"},
	{Code: 904, Name: "Vega de Alatorre", State: "MX-VER"},
	{Code: 905, Name: "Veracruz", State: "MX-VER"},
	{Code: 906, Name: "Xico", State: "MX-VER"},
	{Code: 910, Name: "Mérida", State: "MX-YUC"},
	{Code: 911, Name: "Izamal", State: "MX-YUC"},
	{Code: 912, Name: "Maxcanu", State: "MX-YUC"},
	{Code: 913, Name: "Motul", State: "MX-YUC"},
	{Code: 914, Name: "Oxkutzcab", State: "MX-YUC"},
	{Code: 915, Name: "Puerto Progreso", State: "MX-YUC"},
	{Code: 916, Name: "Tekax", State: "MX-YUC"},
	{Code: 917, Name: "Ticul", State: "MX-YUC"},
	{Code: 918, Name: "Tizimín", State: "MX-YUC"},
	{Code: 919, Name: "Uman", State: "MX-YUC"},
	{Code: 920, Name: "Valladolid", State: "MX-YUC"},
	{Code: 930, Name: "Zacatecas", State: "MX-ZAC"},
	{Code: 931, Name: "Apozol", State: "MX-ZAC"},
	{Code: 932, Name: "Concepcion del Oro", State: "MX-ZAC"},
	{Code: 933, Name: "Fresnillo", State: "MX-ZAC"},
	{Code: 934, Name: "Guadalupe", State: "MX-ZAC"},
	{Code: 935, Name: "Jalpa", State: "MX-ZAC"},
	{Code: 936, Name: "Jerez de Garcia Salinas", State: "MX-ZAC"},
	{Code: 937, Name: "Juan Aldama", State: "MX-ZAC"},
	{Code: 938, Name: "Juchipila", State: "MX-ZAC"},
	{Code: 939, Name: "Loreto", State: "MX-ZAC"},
	{Code: 940, Name: "Luis Moya", State: "MX-ZAC"},
	{Code: 941, Name: "Miguel Auza", State: "MX-ZAC"},
	{Code: 942, Name: "Monte Escobedo", State: "MX-ZAC"},
	{Code: 943, Name: "Morelos", State: "MX-ZAC"},
	{Code: 944, Name: "Moyahua de Estrada", State: "MX-ZAC"},
	{Code: 945, Name: "Nieves", State: "MX-ZAC"},
	{Code: 946, Name: "Nochistlán de Mejia", State: "MX-ZAC"},
	{Code: 947, Name: "Ojocaliente", State: "MX-ZAC"},
	{Code: 948, Name: "Pinos", State: "MX-ZAC"},
	{Code: 949, Name: "Rio Grande", State: "MX-ZAC"},
	{Code: 950, Name: "Sain Alto", State: "MX-ZAC"},
	{Code: 951, Name: "San Pedro Apulco", State: "MX-ZAC"},
	{Code: 952, Name: "Sombrerete", State: "MX-ZAC"},
	{Code: 953, Name: "Tabasco", State: "MX-ZAC"},
	{Code: 954, Name: "Tepechitlan", State: "MX-ZAC"},
	{Code: 955, Name: "Tepetongo", State: "MX-ZAC"},
	{Code: 956, Name: "Teul de Glez. Ortega", State: "MX-ZAC"},
	{Code: 957, Name: "Cosautlan", State: "MX-VER"},
	{Code: 958, Name: "Valparaíso", State: "MX-ZAC"},
	{Code: 959, Name: "Valla de Cos", State: "MX-ZAC"},
	{Code: 960, Name: "Victor Rosales", State: "MX-ZAC"},
	{Code: 961, Name: "Villa Gonzalez Ortega", State: "MX-ZAC"},
	{Code: 962, Name: "Villanueva", State: "MX-ZAC"},
	{Code: 969, Name: "Ciudad de México", State: "MX-CMX"},
}

func ReturnRandomCity() ClabeCityInfo {
	mapLen := len(citiesMap)
	randNumber, err := rand.Int(rand.Reader, big.NewInt(int64(mapLen-1)))
	if err != nil {
		log.Println(err)
	}
	intRandomNumber := int(randNumber.Int64())
	randomCity := citiesMap[intRandomNumber]
	return randomCity
}
