package internal

import (
	"crypto/rand"
	"log"
	"math/big"
)

var citiesMap = ClabeCitiesMap{
	10:  {{Code: 10, Name: "Aguascalientes", State: "MX-AGU"}},
	11:  {{Code: 11, Name: "Asientos", State: "MX-AGU"}},
	12:  {{Code: 12, Name: "Calvillo", State: "MX-AGU"}},
	13:  {{Code: 13, Name: "Cosio", State: "MX-AGU"}},
	14:  {{Code: 14, Name: "Jesús María", State: "MX-AGU"}},
	15:  {{Code: 15, Name: "Pabellon de Arteaga", State: "MX-AGU"}},
	16:  {{Code: 16, Name: "Rincon de Romos", State: "MX-AGU"}},
	17:  {{Code: 17, Name: "San Fco Romo", State: "MX-AGU"}},
	20:  {{Code: 20, Name: "Mexicali", State: "MX-BCN"}},
	21:  {{Code: 21, Name: "Ciudad Morelos", State: "MX-BCN"}},
	22:  {{Code: 22, Name: "Ensenada", State: "MX-BCN"}},
	23:  {{Code: 23, Name: "Guadalupe Victoria", State: "MX-BCN"}},
	24:  {{Code: 24, Name: "Rodolfo Sanchez T.", State: "MX-BCN"}},
	25:  {{Code: 25, Name: "San Felipe", State: "MX-BCN"}},
	26:  {{Code: 26, Name: "San Quintin", State: "MX-BCN"}},
	27:  {{Code: 27, Name: "Tecate", State: "MX-BCN"}},
	28:  {{Code: 28, Name: "Playas de Rosarito", State: "MX-BCN"}},
	40:  {{Code: 40, Name: "La Paz", State: "MX-BCS"}},
	41:  {{Code: 41, Name: "Cabo San Lucas", State: "MX-BCS"}},
	42:  {{Code: 42, Name: "Ciudad Constitución", State: "MX-BCS"}},
	43:  {{Code: 43, Name: "Guerrero Negro", State: "MX-BCS"}},
	44:  {{Code: 44, Name: "Loreto", State: "MX-BCS"}},
	45:  {{Code: 45, Name: "San José del Cabo", State: "MX-BCS"}},
	46:  {{Code: 46, Name: "Santa Rosalía", State: "MX-BCS"}},
	47:  {{Code: 47, Name: "Todos Santos", State: "MX-BCS"}},
	50:  {{Code: 50, Name: "Campeche", State: "MX-CAM"}},
	51:  {{Code: 51, Name: "Calkiní", State: "MX-CAM"}},
	52:  {{Code: 52, Name: "Ciudad del Carmen", State: "MX-CAM"}},
	53:  {{Code: 53, Name: "Champotón", State: "MX-CAM"}},
	54:  {{Code: 54, Name: "Escarcega", State: "MX-CAM"}},
	55:  {{Code: 55, Name: "Hopelchen", State: "MX-CAM"}},
	56:  {{Code: 56, Name: "Palizada", State: "MX-CAM"}},
	57:  {{Code: 57, Name: "Seybaplaya", State: "MX-CAM"}},
	60:  {{Code: 60, Name: "Torreón", State: "MX-COA"}},
	61:  {{Code: 61, Name: "Abasolo", State: "MX-COA"}},
	62:  {{Code: 62, Name: "Acuña", State: "MX-COA"}},
	63:  {{Code: 63, Name: "Allende", State: "MX-COA"}},
	64:  {{Code: 64, Name: "Francisco I. Madero", State: "MX-COA"}},
	65:  {{Code: 65, Name: "Frontera", State: "MX-COA"}},
	66:  {{Code: 66, Name: "Laguna del Rey", State: "MX-COA"}},
	67:  {{Code: 67, Name: "Matamoros", State: "MX-COA"}},
	68:  {{Code: 68, Name: "Monclova", State: "MX-COA"}},
	69:  {{Code: 69, Name: "Morelos", State: "MX-COA"}},
	70:  {{Code: 70, Name: "Muzquiz", State: "MX-COA"}},
	71:  {{Code: 71, Name: "Nava", State: "MX-COA"}},
	72:  {{Code: 72, Name: "Nva Rosita", State: "MX-COA"}},
	73:  {{Code: 73, Name: "Palau", State: "MX-COA"}},
	74:  {{Code: 74, Name: "Parras de la Fuente", State: "MX-COA"}},
	75:  {{Code: 75, Name: "Piedras Negras", State: "MX-COA"}},
	76:  {{Code: 76, Name: "Ramos Arizpe", State: "MX-COA"}},
	77:  {{Code: 77, Name: "Sabinas", State: "MX-COA"}},
	78:  {{Code: 78, Name: "Saltillo", State: "MX-COA"}},
	79:  {{Code: 79, Name: "San Buenaventura", State: "MX-COA"}},
	80:  {{Code: 80, Name: "San Pedro de las Colonias", State: "MX-COA"}},
	81:  {{Code: 81, Name: "Zaragoza", State: "MX-COA"}},
	90:  {{Code: 90, Name: "Colima", State: "MX-COL"}},
	91:  {{Code: 91, Name: "Armeria", State: "MX-COL"}},
	92:  {{Code: 92, Name: "Comala", State: "MX-COL"}},
	93:  {{Code: 93, Name: "Coquimatlan", State: "MX-COL"}},
	94:  {{Code: 94, Name: "Cuauhtemoc", State: "MX-COL"}},
	95:  {{Code: 95, Name: "Manzanillo", State: "MX-COL"}},
	96:  {{Code: 96, Name: "Queseria", State: "MX-COL"}},
	97:  {{Code: 97, Name: "Tecomán", State: "MX-COL"}},
	98:  {{Code: 98, Name: "Villa de Alvarez", State: "MX-COL"}},
	100: {{Code: 100, Name: "Tuxtla Gutiérrez", State: "MX-CHP"}},
	101: {{Code: 101, Name: "Acapetahua", State: "MX-CHP"}},
	102: {{Code: 102, Name: "Angel Albino Corzo", State: "MX-CHP"}},
	103: {{Code: 103, Name: "Arriaga", State: "MX-CHP"}},
	104: {{Code: 104, Name: "Bochil", State: "MX-CHP"}},
	105: {{Code: 105, Name: "Cacahoatan", State: "MX-CHP"}},
	106: {{Code: 106, Name: "Catazaja", State: "MX-CHP"}},
	107: {{Code: 107, Name: "Cintalapa", State: "MX-CHP"}},
	108: {{Code: 108, Name: "Ciudad Hidalgo", State: "MX-CHP"}},
	109: {{Code: 109, Name: "Comitán de Dominguez", State: "MX-CHP"}},
	110: {{Code: 110, Name: "Copainala", State: "MX-CHP"}},
	111: {{Code: 111, Name: "Chiapa de Corso", State: "MX-CHP"}},
	112: {{Code: 112, Name: "Chicomuselo", State: "MX-CHP"}},
	113: {{Code: 113, Name: "Frontera Comalapa", State: "MX-CHP"}},
	114: {{Code: 114, Name: "Huixtla", State: "MX-CHP"}},
	115: {{Code: 115, Name: "Jiquipilas", State: "MX-CHP"}},
	116: {{Code: 116, Name: "Juarez", State: "MX-CHP"}},
	117: {{Code: 117, Name: "La Concordia", State: "MX-CHP"}},
	118: {{Code: 118, Name: "La Trinitaria", State: "MX-CHP"}},
	119: {{Code: 119, Name: "Las Margaritas", State: "MX-CHP"}},
	120: {{Code: 120, Name: "Las Rosas", State: "MX-CHP"}},
	121: {{Code: 121, Name: "Mapastepec", State: "MX-CHP"}},
	122: {{Code: 122, Name: "Motozintla", State: "MX-CHP"}},
	123: {{Code: 123, Name: "Ocosingo", State: "MX-CHP"}},
	124: {{Code: 124, Name: "Ocozocoautla", State: "MX-CHP"}},
	125: {{Code: 125, Name: "Palenque", State: "MX-CHP"}},
	126: {{Code: 126, Name: "Pichucalco", State: "MX-CHP"}},
	127: {{Code: 127, Name: "Pijijiapan", State: "MX-CHP"}},
	128: {{Code: 128, Name: "Reforma", State: "MX-CHP"}},
	129: {{Code: 129, Name: "Salto de Agua", State: "MX-CHP"}},
	130: {{Code: 130, Name: "San Cristóbal de las Casas", State: "MX-CHP"}},
	131: {{Code: 131, Name: "Simojovel", State: "MX-CHP"}},
	132: {{Code: 132, Name: "Socoltenango", State: "MX-CHP"}},
	133: {{Code: 133, Name: "Tapachula", State: "MX-CHP"}},
	134: {{Code: 134, Name: "Teopisca", State: "MX-CHP"}},
	135: {{Code: 135, Name: "Tonala", State: "MX-CHP"}},
	136: {{Code: 136, Name: "Tuxtla Chico", State: "MX-CHP"}},
	137: {{Code: 137, Name: "Venustiano Carranza", State: "MX-CHP"}},
	138: {{Code: 138, Name: "Villa Corzo", State: "MX-CHP"}},
	140: {{Code: 140, Name: "Yajalón", State: "MX-CHP"}},
	150: {{Code: 150, Name: "Chihuahua", State: "MX-CHH"}},
	151: {{Code: 151, Name: "Ahumada", State: "MX-CHH"}},
	152: {{Code: 152, Name: "Anahuac", State: "MX-CHH"}},
	153: {{Code: 153, Name: "Ascension", State: "MX-CHH"}},
	154: {{Code: 154, Name: "Buenaventura", State: "MX-CHH"}},
	155: {{Code: 155, Name: "Camargo", State: "MX-CHH"}},
	156: {{Code: 156, Name: "Casas Grandes", State: "MX-CHH"}},
	157: {{Code: 157, Name: "Creel", State: "MX-CHH"}},
	158: {{Code: 158, Name: "Cuauhtemoc", State: "MX-CHH"}},
	159: {{Code: 159, Name: "Gomez Farias", State: "MX-CHH"}},
	160: {{Code: 160, Name: "Guachochi", State: "MX-CHH"}},
	161: {{Code: 161, Name: "Guerrero", State: "MX-CHH"}},
	162: {{Code: 162, Name: "Hidalgo del Parral", State: "MX-CHH"}},
	163: {{Code: 163, Name: "Ciudad Jiménez", State: "MX-CHH"}},
	164: {{Code: 164, Name: "Ciudad Juárez", State: "MX-CHH"}},
	165: {{Code: 165, Name: "Madera", State: "MX-CHH"}},
	166: {{Code: 166, Name: "Meoqui", State: "MX-CHH"}},
	167: {{Code: 167, Name: "Nameiquipa", State: "MX-CHH"}},
	168: {{Code: 168, Name: "Nvo Casas Grandes", State: "MX-CHH"}},
	169: {{Code: 169, Name: "Ojinaga", State: "MX-CHH"}},
	170: {{Code: 170, Name: "Praxedis G. Guerrero", State: "MX-CHH"}},
	171: {{Code: 171, Name: "Puerto Palomas", State: "MX-CHH"}},
	172: {{Code: 172, Name: "Santa Barbara", State: "MX-CHH"}},
	173: {{Code: 173, Name: "Saucillo", State: "MX-CHH"}},
	180: {{Code: 180, Name: "Ciudad de México", State: "MX-CMX"}},
	190: {{Code: 190, Name: "Durango", State: "MX-DUR"}},
	191: {{Code: 191, Name: "Canatlan", State: "MX-DUR"}},
	192: {{Code: 192, Name: "Cuencame", State: "MX-DUR"}},
	193: {{Code: 193, Name: "El Salto", State: "MX-DUR"}},
	194: {{Code: 194, Name: "Guadalupe Victoria", State: "MX-DUR"}},
	195: {{Code: 195, Name: "Nazas", State: "MX-DUR"}},
	196: {{Code: 196, Name: "Nvo Ideal", State: "MX-DUR"}},
	197: {{Code: 197, Name: "San Juan del Rio", State: "MX-DUR"}},
	198: {{Code: 198, Name: "Santa Maria del Oro", State: "MX-DUR"}},
	199: {{Code: 199, Name: "Santiago Papasquiaro", State: "MX-DUR"}},
	200: {{Code: 200, Name: "Tayoltita", State: "MX-DUR"}},
	201: {{Code: 201, Name: "Tepehuanes", State: "MX-DUR"}},
	202: {{Code: 202, Name: "Vicente Guerrero", State: "MX-DUR"}},
	210: {{Code: 210, Name: "Guanajuato", State: "MX-GUA"}},
	211: {{Code: 211, Name: "Abasolo", State: "MX-GUA"}},
	212: {{Code: 212, Name: "Acámbaro", State: "MX-GUA"}},
	213: {{Code: 213, Name: "Apaseo el Alto", State: "MX-GUA"}},
	214: {{Code: 214, Name: "Apaseo el Grande", State: "MX-GUA"}},
	215: {{Code: 215, Name: "Celaya", State: "MX-GUA"}},
	216: {{Code: 216, Name: "Comonfort", State: "MX-GUA"}},
	217: {{Code: 217, Name: "Coroneo", State: "MX-GUA"}},
	218: {{Code: 218, Name: "Cortazar", State: "MX-GUA"}},
	219: {{Code: 219, Name: "Cuerámaro", State: "MX-GUA"}},
	220: {{Code: 220, Name: "Dolores Hidalgo", State: "MX-GUA"}},
	221: {{Code: 221, Name: "Huanimaro", State: "MX-GUA"}},
	222: {{Code: 222, Name: "Irapuato", State: "MX-GUA"}},
	223: {{Code: 223, Name: "Jaral del Progreso", State: "MX-GUA"}},
	224: {{Code: 224, Name: "Jerécuaro", State: "MX-GUA"}},
	225: {{Code: 225, Name: "León", State: "MX-GUA"}},
	226: {{Code: 226, Name: "Manuel Doblado", State: "MX-GUA"}},
	227: {{Code: 227, Name: "Moroleón", State: "MX-GUA"}},
	228: {{Code: 228, Name: "Ocampo", State: "MX-GUA"}},
	229: {{Code: 229, Name: "Pénjamo", State: "MX-GUA"}},
	230: {{Code: 230, Name: "Pueblo Nuevo", State: "MX-GUA"}},
	231: {{Code: 231, Name: "Purisima del Rincon", State: "MX-GUA"}},
	232: {{Code: 232, Name: "Romita", State: "MX-GUA"}},
	233: {{Code: 233, Name: "Salamanca", State: "MX-GUA"}},
	234: {{Code: 234, Name: "Salvatierra", State: "MX-GUA"}},
	235: {{Code: 235, Name: "San Diego de la Union", State: "MX-GUA"}},
	236: {{Code: 236, Name: "San Felipe Progreso", State: "MX-GUA"}},
	237: {{Code: 237, Name: "San Francisco del Rincoón", State: "MX-GUA"}},
	238: {{Code: 238, Name: "San José Iturbide", State: "MX-GUA"}},
	239: {{Code: 239, Name: "San Luis de la Paz", State: "MX-GUA"}},
	240: {{Code: 240, Name: "San Miguel de Allende", State: "MX-GUA"}},
	241: {{Code: 241, Name: "Santa Ana Pacueco", State: "MX-GUA"}},
	242: {{Code: 242, Name: "Santa Cruz de Juventino", State: "MX-GUA"}},
	243: {{Code: 243, Name: "Santiago Maravatio", State: "MX-GUA"}},
	244: {{Code: 244, Name: "Silao", State: "MX-GUA"}},
	245: {{Code: 245, Name: "Tarandacuao", State: "MX-GUA"}},
	246: {{Code: 246, Name: "Tarimoro", State: "MX-GUA"}},
	247: {{Code: 247, Name: "Uriangato", State: "MX-GUA"}},
	248: {{Code: 248, Name: "Valle de Santiago", State: "MX-GUA"}},
	249: {{Code: 249, Name: "Yuriria", State: "MX-GUA"}},
	260: {{Code: 260, Name: "Chilpancingo", State: "MX-GRO"}},
	261: {{Code: 261, Name: "Acapulco de Juarez", State: "MX-GRO"}},
	262: {{Code: 262, Name: "Apaxtla de Castrejon", State: "MX-GRO"}},
	263: {{Code: 263, Name: "Arcelia", State: "MX-GRO"}},
	264: {{Code: 264, Name: "Atoyac de Álvarez", State: "MX-GRO"}},
	265: {{Code: 265, Name: "Buenavista de Cuellar", State: "MX-GRO"}},
	266: {{Code: 266, Name: "Ciudad Altamirano", State: "MX-GRO"}},
	267: {{Code: 267, Name: "Coyuca de Benítez", State: "MX-GRO"}},
	268: {{Code: 268, Name: "Cruz Grande", State: "MX-GRO"}},
	269: {{Code: 269, Name: "Chichihualco", State: "MX-GRO"}},
	270: {{Code: 270, Name: "Chilapa de Alvarez", State: "MX-GRO"}},
	271: {{Code: 271, Name: "Huitzuco", State: "MX-GRO"}},
	272: {{Code: 272, Name: "Iguala", State: "MX-GRO"}},
	273: {{Code: 273, Name: "Olinala", State: "MX-GRO"}},
	274: {{Code: 274, Name: "Ometepec", State: "MX-GRO"}},
	275: {{Code: 275, Name: "San Marcos", State: "MX-GRO"}},
	276: {{Code: 276, Name: "Taxco de Alarcon", State: "MX-GRO"}},
	277: {{Code: 277, Name: "Petatlan", State: "MX-GRO"}},
	278: {{Code: 278, Name: "Teloloapan", State: "MX-GRO"}},
	279: {{Code: 279, Name: "Tierra Colorada", State: "MX-GRO"}},
	280: {{Code: 280, Name: "Tixtla de Guerrero", State: "MX-GRO"}},
	281: {{Code: 281, Name: "Tlapa de Comonfort", State: "MX-GRO"}},
	282: {{Code: 282, Name: "Ixtapa Zihuatanejo", State: "MX-GRO"}},
	290: {{Code: 290, Name: "Pachuca de Soto", State: "MX-HID"}},
	291: {{Code: 291, Name: "Actopan", State: "MX-HID"}},
	292: {{Code: 292, Name: "Apam", State: "MX-HID"}},
	293: {{Code: 293, Name: "Atotonilco el Grande", State: "MX-HID"}},
	294: {{Code: 294, Name: "Ciudad Sahagún", State: "MX-HID"}},
	295: {{Code: 295, Name: "Cuautepec de Hinojosa", State: "MX-HID"}},
	296: {{Code: 296, Name: "Huejutla de Reyes", State: "MX-HID"}},
	297: {{Code: 297, Name: "Huichapan", State: "MX-HID"}},
	298: {{Code: 298, Name: "Ixmiquilpan", State: "MX-HID"}},
	299: {{Code: 299, Name: "Jacala", State: "MX-HID"}},
	300: {{Code: 300, Name: "Metztitlan", State: "MX-HID"}},
	301: {{Code: 301, Name: "Mixquiahuala", State: "MX-HID"}},
	302: {{Code: 302, Name: "Molango", State: "MX-HID"}},
	303: {{Code: 303, Name: "Progreso de Obregón", State: "MX-HID"}},
	304: {{Code: 304, Name: "Tasquillo", State: "MX-HID"}},
	305: {{Code: 305, Name: "Tepeapulco", State: "MX-HID"}},
	306: {{Code: 306, Name: "Tepeji del Rio", State: "MX-HID"}},
	307: {{Code: 307, Name: "Tezontepec", State: "MX-HID"}},
	308: {{Code: 308, Name: "Tizayuca", State: "MX-HID"}},
	309: {{Code: 309, Name: "Tlahuelilpan", State: "MX-HID"}},
	310: {{Code: 310, Name: "Tlaxcoapan", State: "MX-HID"}},
	311: {{Code: 311, Name: "Tula de Allende", State: "MX-HID"}},
	312: {{Code: 312, Name: "Tulancingo", State: "MX-HID"}},
	313: {{Code: 313, Name: "Zacualtipán", State: "MX-HID"}},
	314: {{Code: 314, Name: "Zimapán", State: "MX-HID"}},
	320: {{Code: 320, Name: "El Salto", State: "MX-JAL"}},
	321: {{Code: 321, Name: "Acatic", State: "MX-JAL"}},
	322: {{Code: 322, Name: "Acatlan de Juarez", State: "MX-JAL"}},
	323: {{Code: 323, Name: "Ahualulco de Mercado", State: "MX-JAL"}},
	324: {{Code: 324, Name: "Ajijic", State: "MX-JAL"}},
	325: {{Code: 325, Name: "Amatitan", State: "MX-JAL"}},
	326: {{Code: 326, Name: "Ameca", State: "MX-JAL"}},
	327: {{Code: 327, Name: "Arandas", State: "MX-JAL"}},
	328: {{Code: 328, Name: "Arenal", State: "MX-JAL"}},
	329: {{Code: 329, Name: "Atenguillo", State: "MX-JAL"}},
	330: {{Code: 330, Name: "Atotonilco el Alto", State: "MX-JAL"}},
	331: {{Code: 331, Name: "Atotonilquillo", State: "MX-JAL"}},
	332: {{Code: 332, Name: "Atoyac", State: "MX-JAL"}},
	333: {{Code: 333, Name: "Autlán de Navarro", State: "MX-JAL"}},
	334: {{Code: 334, Name: "Ayotlan", State: "MX-JAL"}},
	335: {{Code: 335, Name: "Ayutla", State: "MX-JAL"}},
	336: {{Code: 336, Name: "Bajio de San Jose", State: "MX-JAL"}},
	337: {{Code: 337, Name: "Belen del Refugio", State: "MX-JAL"}},
	338: {{Code: 338, Name: "Cañadas de Obregon", State: "MX-JAL"}},
	339: {{Code: 339, Name: "Capilla de Guadalupe", State: "MX-JAL"}},
	340: {{Code: 340, Name: "Casimiro Castillo", State: "MX-JAL"}},
	341: {{Code: 341, Name: "Cihuatlán", State: "MX-JAL"}},
	342: {{Code: 342, Name: "Ciudad Guzmán", State: "MX-JAL"}},
	343: {{Code: 343, Name: "Cocula", State: "MX-JAL"}},
	344: {{Code: 344, Name: "Ixtlixochitl", State: "MX-MEX"}},
	345: {{Code: 345, Name: "Cuquio", State: "MX-JAL"}},
	346: {{Code: 346, Name: "Chapala", State: "MX-JAL"}},
	347: {{Code: 347, Name: "Degollado", State: "MX-JAL"}},
	348: {{Code: 348, Name: "El Grullo", State: "MX-JAL"}},
	349: {{Code: 349, Name: "Encarnacion de Diaz", State: "MX-JAL"}},
	350: {{Code: 350, Name: "Estipac", State: "MX-JAL"}},
	351: {{Code: 351, Name: "Guachinango", State: "MX-JAL"}},
	352: {{Code: 352, Name: "Huejucar", State: "MX-JAL"}},
	353: {{Code: 353, Name: "Huejuquilla el Alto", State: "MX-JAL"}},
	354: {{Code: 354, Name: "Ixtlahuacan de los M.", State: "MX-JAL"}},
	355: {{Code: 355, Name: "Ixtlahuacán del Río", State: "MX-JAL"}},
	356: {{Code: 356, Name: "Jalostotitlán", State: "MX-JAL"}},
	357: {{Code: 357, Name: "Jamay", State: "MX-JAL"}},
	358: {{Code: 358, Name: "Jesus Maria", State: "MX-JAL"}},
	359: {{Code: 359, Name: "Jocotepec", State: "MX-JAL"}},
	360: {{Code: 360, Name: "Juchitlan", State: "MX-JAL"}},
	361: {{Code: 361, Name: "La Barca", State: "MX-JAL"}},
	362: {{Code: 362, Name: "Lagos de Moreno", State: "MX-JAL"}},
	363: {{Code: 363, Name: "Magdalena", State: "MX-JAL"}},
	364: {{Code: 364, Name: "Manzanilla de la Paz", State: "MX-JAL"}},
	365: {{Code: 365, Name: "Mascota", State: "MX-JAL"}},
	366: {{Code: 366, Name: "Mazamitla", State: "MX-JAL"}},
	367: {{Code: 367, Name: "Mexticacan", State: "MX-JAL"}},
	368: {{Code: 368, Name: "Mezquitic", State: "MX-JAL"}},
	369: {{Code: 369, Name: "Mixtlan", State: "MX-JAL"}},
	370: {{Code: 370, Name: "Ocotlán", State: "MX-JAL"}},
	371: {{Code: 371, Name: "Ojuelos de Jalisco", State: "MX-JAL"}},
	372: {{Code: 372, Name: "Pegueros", State: "MX-JAL"}},
	373: {{Code: 373, Name: "Pihuamo", State: "MX-JAL"}},
	374: {{Code: 374, Name: "Poncitlan", State: "MX-JAL"}},
	375: {{Code: 375, Name: "Puerto Vallarta", State: "MX-JAL"}},
	376: {{Code: 376, Name: "Purificacion", State: "MX-JAL"}},
	377: {{Code: 377, Name: "Quitupan", State: "MX-JAL"}},
	378: {{Code: 378, Name: "San Ignacio Cerro G.", State: "MX-JAL"}},
	379: {{Code: 379, Name: "San Jose Casas Caidas", State: "MX-JAL"}},
	380: {{Code: 380, Name: "San Jose de Gracia", State: "MX-JAL"}},
	381: {{Code: 381, Name: "San Juan de los Lagos", State: "MX-JAL"}},
	382: {{Code: 382, Name: "San Julian", State: "MX-JAL"}},
	383: {{Code: 383, Name: "San Martin Hidalgo", State: "MX-JAL"}},
	384: {{Code: 384, Name: "San Miguel el Alto", State: "MX-JAL"}},
	385: {{Code: 385, Name: "San Patricio Melaque", State: "MX-JAL"}},
	386: {{Code: 386, Name: "Sayula", State: "MX-JAL"}},
	387: {{Code: 387, Name: "Tala", State: "MX-JAL"}},
	388: {{Code: 388, Name: "Talpa de Allende", State: "MX-JAL"}},
	389: {{Code: 389, Name: "Tamazula de Gordiano", State: "MX-JAL"}},
	390: {{Code: 390, Name: "Tapalpa", State: "MX-JAL"}},
	391: {{Code: 391, Name: "Tecalitlán", State: "MX-JAL"}},
	392: {{Code: 392, Name: "Tecolotlan", State: "MX-JAL"}},
	393: {{Code: 393, Name: "TeNameaxtlan", State: "MX-JAL"}},
	394: {{Code: 394, Name: "Teocaltiche", State: "MX-JAL"}},
	395: {{Code: 395, Name: "Teocuitatlan de Corona", State: "MX-JAL"}},
	396: {{Code: 396, Name: "Tepatitlán de Morelos", State: "MX-JAL"}},
	397: {{Code: 397, Name: "Tequila", State: "MX-JAL"}},
	398: {{Code: 398, Name: "Tizapan el Alto", State: "MX-JAL"}},
	399: {{Code: 399, Name: "Toliman", State: "MX-JAL"}},
	400: {{Code: 400, Name: "Tomatlan", State: "MX-JAL"}},
	401: {{Code: 401, Name: "Tonaya", State: "MX-JAL"}},
	402: {{Code: 402, Name: "Totatiche", State: "MX-JAL"}},
	403: {{Code: 403, Name: "Tototlán", State: "MX-JAL"}},
	404: {{Code: 404, Name: "Tuxpan", State: "MX-JAL"}},
	405: {{Code: 405, Name: "Union de San Antonio", State: "MX-JAL"}},
	406: {{Code: 406, Name: "Union de Tula", State: "MX-JAL"}},
	407: {{Code: 407, Name: "Valle de Guadalupe", State: "MX-JAL"}},
	408: {{Code: 408, Name: "Valle de Juarez", State: "MX-JAL"}},
	409: {{Code: 409, Name: "Villa Corona", State: "MX-JAL"}},
	410: {{Code: 410, Name: "Villa Guerrero", State: "MX-JAL"}},
	411: {{Code: 411, Name: "Villa Hidalgo", State: "MX-JAL"}},
	412: {{Code: 412, Name: "Vista Hermosa", State: "MX-JAL"}},
	413: {{Code: 413, Name: "Zacoalco de Torres", State: "MX-JAL"}},
	414: {{Code: 414, Name: "Zapotiltic", State: "MX-JAL"}},
	415: {{Code: 415, Name: "Zapotlan del Rey", State: "MX-JAL"}},
	416: {{Code: 416, Name: "Zapotlanejo", State: "MX-JAL"}},
	420: {{Code: 420, Name: "Toluca", State: "MX-MEX"}},
	421: {{Code: 421, Name: "Acambay", State: "MX-MEX"}},
	422: {{Code: 422, Name: "Almoloya de Juárez", State: "MX-MEX"}},
	423: {{Code: 423, Name: "Amatepec", State: "MX-MEX"}},
	424: {{Code: 424, Name: "Amecameca", State: "MX-MEX"}},
	425: {{Code: 425, Name: "Apaxco", State: "MX-MEX"}},
	426: {{Code: 426, Name: "Atlacomulco", State: "MX-MEX"}},
	427: {{Code: 427, Name: "Capulhuac", State: "MX-MEX"}},
	428: {{Code: 428, Name: "Coatepec de Harinas", State: "MX-MEX"}},
	429: {{Code: 429, Name: "Colorines", State: "MX-MEX"}},
	430: {{Code: 430, Name: "Chicoloapan", State: "MX-MEX"}},
	431: {{Code: 431, Name: "Chiconcuac", State: "MX-MEX"}},
	432: {{Code: 432, Name: "El Oro", State: "MX-MEX"}},
	433: {{Code: 433, Name: "Ixtapan de la Sal", State: "MX-MEX"}},
	434: {{Code: 434, Name: "Ixtlahuaca", State: "MX-MEX"}},
	435: {{Code: 435, Name: "Jilotepec", State: "MX-MEX"}},
	436: {{Code: 436, Name: "Jocotitlan", State: "MX-MEX"}},
	437: {{Code: 437, Name: "Chimalhuacan", State: "MX-MEX"}},
	438: {{Code: 438, Name: "Lerma", State: "MX-MEX"}},
	439: {{Code: 439, Name: "Luvianos", State: "MX-MEX"}},
	440: {{Code: 440, Name: "Malinalco", State: "MX-MEX"}},
	441: {{Code: 441, Name: "Metepec", State: "MX-MEX"}},
	442: {{Code: 442, Name: "Ocoyoacac", State: "MX-MEX"}},
	443: {{Code: 443, Name: "Otumba", State: "MX-MEX"}},
	444: {{Code: 444, Name: "San Felipe Progreso", State: "MX-MEX"}},
	445: {{Code: 445, Name: "San Mateo Atenco", State: "MX-MEX"}},
	446: {{Code: 446, Name: "Tejupilco", State: "MX-MEX"}},
	447: {{Code: 447, Name: "Temascalcingo", State: "MX-MEX"}},
	448: {{Code: 448, Name: "Temascaltepec", State: "MX-MEX"}},
	449: {{Code: 449, Name: "Temoaya", State: "MX-MEX"}},
	450: {{Code: 450, Name: "Tenancingo", State: "MX-MEX"}},
	451: {{Code: 451, Name: "Tenango de Arista", State: "MX-MEX"}},
	452: {{Code: 452, Name: "Texcaltitlan", State: "MX-MEX"}},
	453: {{Code: 453, Name: "Tianguistenco", State: "MX-MEX"}},
	454: {{Code: 454, Name: "Tonatico", State: "MX-MEX"}},
	455: {{Code: 455, Name: "Tultepec", State: "MX-MEX"}},
	456: {{Code: 456, Name: "Tultitlán", State: "MX-MEX"}},
	457: {{Code: 457, Name: "Valle de Bravo", State: "MX-MEX"}},
	458: {{Code: 458, Name: "Villa del Carbon", State: "MX-MEX"}},
	459: {{Code: 459, Name: "Villa Guerrero", State: "MX-MEX"}},
	460: {{Code: 460, Name: "Villa Nicolás Romero", State: "MX-MEX"}},
	461: {{Code: 461, Name: "Villa Victoria", State: "MX-MEX"}},
	462: {{Code: 462, Name: "Xonacatlan", State: "MX-MEX"}},
	463: {{Code: 463, Name: "Zumpango", State: "MX-MEX"}},
	470: {{Code: 470, Name: "Morelia", State: "MX-MIC"}},
	471: {{Code: 471, Name: "Acuitzio del Canje", State: "MX-MIC"}},
	472: {{Code: 472, Name: "Aguililla", State: "MX-MIC"}},
	473: {{Code: 473, Name: "Alvaro Obregon", State: "MX-MIC"}},
	474: {{Code: 474, Name: "Angamacutiro", State: "MX-MIC"}},
	475: {{Code: 475, Name: "Angangueo", State: "MX-MIC"}},
	476: {{Code: 476, Name: "Apatzingán", State: "MX-MIC"}},
	477: {{Code: 477, Name: "Ario de Rosales", State: "MX-MIC"}},
	478: {{Code: 478, Name: "Arteaga", State: "MX-MIC"}},
	479: {{Code: 479, Name: "Buenavista Tomatlan", State: "MX-MIC"}},
	480: {{Code: 480, Name: "Ciudad Hidalgo", State: "MX-MIC"}},
	481: {{Code: 481, Name: "Coalcoman de Vazquez", State: "MX-MIC"}},
	482: {{Code: 482, Name: "Contepec", State: "MX-MIC"}},
	483: {{Code: 483, Name: "Cotija de la Paz", State: "MX-MIC"}},
	484: {{Code: 484, Name: "Cuitzeo", State: "MX-MIC"}},
	485: {{Code: 485, Name: "Chavinda", State: "MX-MIC"}},
	486: {{Code: 486, Name: "Cheran", State: "MX-MIC"}},
	487: {{Code: 487, Name: "Chilchota", State: "MX-MIC"}},
	488: {{Code: 488, Name: "Churintzio", State: "MX-MIC"}},
	489: {{Code: 489, Name: "Epitacio Huerta", State: "MX-MIC"}},
	490: {{Code: 490, Name: "Gabriel Zamora", State: "MX-MIC"}},
	491: {{Code: 491, Name: "Huandacareo", State: "MX-MIC"}},
	492: {{Code: 492, Name: "Huetamo", State: "MX-MIC"}},
	493: {{Code: 493, Name: "Jacona de Plancarte", State: "MX-MIC"}},
	494: {{Code: 494, Name: "Jiquilpan de Juarez", State: "MX-MIC"}},
	495: {{Code: 495, Name: "La Huacana", State: "MX-MIC"}},
	496: {{Code: 496, Name: "La Piedad de Cabadas", State: "MX-MIC"}},
	497: {{Code: 497, Name: "Lázaro Cárdenas", State: "MX-MIC"}},
	498: {{Code: 498, Name: "Los Reyes de Salgado", State: "MX-MIC"}},
	499: {{Code: 499, Name: "Maravatío", State: "MX-MIC"}},
	500: {{Code: 500, Name: "San Jose de Gracia", State: "MX-MIC"}},
	501: {{Code: 501, Name: "Nva Italia de Ruiz", State: "MX-MIC"}},
	502: {{Code: 502, Name: "Pajacuaran", State: "MX-MIC"}},
	503: {{Code: 503, Name: "Panindicuaro", State: "MX-MIC"}},
	504: {{Code: 504, Name: "Paracho", State: "MX-MIC"}},
	505: {{Code: 505, Name: "Pastor Ortiz", State: "MX-MIC"}},
	506: {{Code: 506, Name: "Pátzcuaro", State: "MX-MIC"}},
	507: {{Code: 507, Name: "Periban", State: "MX-MIC"}},
	508: {{Code: 508, Name: "Purépero de Echaiz", State: "MX-MIC"}},
	509: {{Code: 509, Name: "Puruandiro", State: "MX-MIC"}},
	510: {{Code: 510, Name: "Querendaro", State: "MX-MIC"}},
	511: {{Code: 511, Name: "Quiroga", State: "MX-MIC"}},
	512: {{Code: 512, Name: "Sahuayo de Morelos", State: "MX-MIC"}},
	513: {{Code: 513, Name: "Santa Ana Maya", State: "MX-MIC"}},
	514: {{Code: 514, Name: "Santiago Tangamandapio", State: "MX-MIC"}},
	515: {{Code: 515, Name: "Tacámbaro Codallos", State: "MX-MIC"}},
	516: {{Code: 516, Name: "Tancitaro", State: "MX-MIC"}},
	517: {{Code: 517, Name: "Tangancícuaro Arista", State: "MX-MIC"}},
	518: {{Code: 518, Name: "Tanhuato de Guerrero", State: "MX-MIC"}},
	519: {{Code: 519, Name: "Tapalcatepec", State: "MX-MIC"}},
	520: {{Code: 520, Name: "Taretan", State: "MX-MIC"}},
	521: {{Code: 521, Name: "Tinguindin", State: "MX-MIC"}},
	522: {{Code: 522, Name: "Tlalpujahua", State: "MX-MIC"}},
	523: {{Code: 523, Name: "Tlazazalca", State: "MX-MIC"}},
	524: {{Code: 524, Name: "Tocumbo", State: "MX-MIC"}},
	525: {{Code: 525, Name: "Tuxpan", State: "MX-MIC"}},
	526: {{Code: 526, Name: "Tuzantla", State: "MX-MIC"}},
	527: {{Code: 527, Name: "Ucareo", State: "MX-MIC"}},
	528: {{Code: 528, Name: "Uruapan", State: "MX-MIC"}},
	529: {{Code: 529, Name: "Villa Jimenez", State: "MX-MIC"}},
	530: {{Code: 530, Name: "Villamar", State: "MX-MIC"}},
	531: {{Code: 531, Name: "Villa Morelos", State: "MX-MIC"}},
	532: {{Code: 532, Name: "Vista Hermosa Negrete", State: "MX-MIC"}},
	533: {{Code: 533, Name: "Yurécuaro", State: "MX-MIC"}},
	534: {{Code: 534, Name: "Zacapu", State: "MX-MIC"}},
	535: {{Code: 535, Name: "Zamora", State: "MX-MIC"}},
	536: {{Code: 536, Name: "Zinapécuaro", State: "MX-MIC"}},
	537: {{Code: 537, Name: "Zitácuaro", State: "MX-MIC"}},
	540: {{Code: 540, Name: "Cuernavaca", State: "MX-MOR"}},
	541: {{Code: 541, Name: "Axochiapan", State: "MX-MOR"}},
	542: {{Code: 542, Name: "Cuautla", State: "MX-MOR"}},
	543: {{Code: 543, Name: "Jiutepec", State: "MX-MOR"}},
	544: {{Code: 544, Name: "Jojutla", State: "MX-MOR"}},
	545: {{Code: 545, Name: "Puente de Ixtla", State: "MX-MOR"}},
	546: {{Code: 546, Name: "Temixco", State: "MX-MOR"}},
	547: {{Code: 547, Name: "Tepoztlan", State: "MX-MOR"}},
	548: {{Code: 548, Name: "Tetecala", State: "MX-MOR"}},
	549: {{Code: 549, Name: "Yautepec", State: "MX-MOR"}},
	551: {{Code: 551, Name: "Yecapixtla", State: "MX-MOR"}},
	552: {{Code: 552, Name: "Zacatepec", State: "MX-MOR"}},
	560: {{Code: 560, Name: "Tepic", State: "MX-NAY"}},
	561: {{Code: 561, Name: "Acaponeta", State: "MX-NAY"}},
	562: {{Code: 562, Name: "Ahuacatlán", State: "MX-NAY"}},
	563: {{Code: 563, Name: "Amatlan de Cañas", State: "MX-NAY"}},
	564: {{Code: 564, Name: "Compostela", State: "MX-NAY"}},
	565: {{Code: 565, Name: "Huajicori", State: "MX-NAY"}},
	566: {{Code: 566, Name: "Ixtlán del Río", State: "MX-NAY"}},
	567: {{Code: 567, Name: "La Penita de Jaltemba", State: "MX-NAY"}},
	568: {{Code: 568, Name: "Las Varas", State: "MX-NAY"}},
	569: {{Code: 569, Name: "Rosamorada", State: "MX-NAY"}},
	570: {{Code: 570, Name: "Ruiz", State: "MX-NAY"}},
	571: {{Code: 571, Name: "San Blas", State: "MX-NAY"}},
	572: {{Code: 572, Name: "Santa Maria del Oro", State: "MX-NAY"}},
	573: {{Code: 573, Name: "Santiago Ixcuintla", State: "MX-NAY"}},
	574: {{Code: 574, Name: "Tecuala", State: "MX-NAY"}},
	575: {{Code: 575, Name: "Túxpam", State: "MX-NAY"}},
	576: {{Code: 576, Name: "Villa Hidalgo", State: "MX-NAY"}},
	577: {{Code: 577, Name: "Xalisco", State: "MX-NAY"}},
	580: {{Code: 580, Name: "Apodaca", State: "MX-NLE"}},
	581: {{Code: 581, Name: "Abasolo", State: "MX-NLE"}},
	582: {{Code: 582, Name: "Agualeguas", State: "MX-NLE"}},
	583: {{Code: 583, Name: "Allende", State: "MX-NLE"}},
	584: {{Code: 584, Name: "Anahuac", State: "MX-NLE"}},
	585: {{Code: 585, Name: "Bustamante", State: "MX-NLE"}},
	586: {{Code: 586, Name: "Cerralvo", State: "MX-NLE"}},
	587: {{Code: 587, Name: "Cienega de Flores", State: "MX-NLE"}},
	588: {{Code: 588, Name: "China", State: "MX-NLE"}},
	589: {{Code: 589, Name: "Galeana", State: "MX-NLE"}},
	590: {{Code: 590, Name: "General Bravo", State: "MX-NLE"}},
	591: {{Code: 591, Name: "General Teran", State: "MX-NLE"}},
	592: {{Code: 592, Name: "General Zuazua", State: "MX-NLE"}},
	593: {{Code: 593, Name: "Hidalgo", State: "MX-NLE"}},
	594: {{Code: 594, Name: "Lampazos de Naranjo", State: "MX-NLE"}},
	595: {{Code: 595, Name: "Linares", State: "MX-NLE"}},
	596: {{Code: 596, Name: "Los Ramones", State: "MX-NLE"}},
	597: {{Code: 597, Name: "Montemorelos", State: "MX-NLE"}},
	598: {{Code: 598, Name: "Pesqueria", State: "MX-NLE"}},
	599: {{Code: 599, Name: "Sabinas Hidalgo", State: "MX-NLE"}},
	600: {{Code: 600, Name: "Salinas Victoria", State: "MX-NLE"}},
	601: {{Code: 601, Name: "Santiago", State: "MX-NLE"}},
	610: {{Code: 610, Name: "Oaxaca", State: "MX-OAX"}},
	611: {{Code: 611, Name: "Asuncion Nochixtlan", State: "MX-OAX"}},
	612: {{Code: 612, Name: "Guelatao", State: "MX-OAX"}},
	613: {{Code: 613, Name: "Heroica Cd de Tlaxiaco", State: "MX-OAX"}},
	614: {{Code: 614, Name: "Huajuapan de León", State: "MX-OAX"}},
	615: {{Code: 615, Name: "Huautla", State: "MX-OAX"}},
	616: {{Code: 616, Name: "Ixtepec", State: "MX-OAX"}},
	617: {{Code: 617, Name: "Juchitán de Zaragoza", State: "MX-OAX"}},
	618: {{Code: 618, Name: "La Reforma", State: "MX-OAX"}},
	619: {{Code: 619, Name: "Loma Bonita", State: "MX-OAX"}},
	620: {{Code: 620, Name: "Matías Romero", State: "MX-OAX"}},
	621: {{Code: 621, Name: "Miahuatlán", State: "MX-OAX"}},
	622: {{Code: 622, Name: "Ocotlán", State: "MX-OAX"}},
	623: {{Code: 623, Name: "Pinotepa", State: "MX-OAX"}},
	624: {{Code: 624, Name: "Puerto Escondido", State: "MX-OAX"}},
	625: {{Code: 625, Name: "Putla", State: "MX-OAX"}},
	626: {{Code: 626, Name: "Salina Cruz", State: "MX-OAX"}},
	627: {{Code: 627, Name: "San Andres Lagunas", State: "MX-OAX"}},
	628: {{Code: 628, Name: "San Juan Bautista T.", State: "MX-OAX"}},
	629: {{Code: 629, Name: "San Pedro Mixtepec", State: "MX-OAX"}},
	630: {{Code: 630, Name: "San Pedro Pochutla", State: "MX-OAX"}},
	631: {{Code: 631, Name: "San Pedro Tapanatepec", State: "MX-OAX"}},
	632: {{Code: 632, Name: "Santa Lucía del Camino", State: "MX-OAX"}},
	633: {{Code: 633, Name: "Santa Maria del Tule", State: "MX-OAX"}},
	634: {{Code: 634, Name: "Santa Maria Huatulco", State: "MX-OAX"}},
	635: {{Code: 635, Name: "Santiago Juxtlahuaca", State: "MX-OAX"}},
	636: {{Code: 636, Name: "Santiago Pinotepa Nal", State: "MX-OAX"}},
	637: {{Code: 637, Name: "Sto Domingo Tehuantepec", State: "MX-OAX"}},
	638: {{Code: 638, Name: "Tlacolula D Matamoros", State: "MX-OAX"}},
	639: {{Code: 639, Name: "Villa de Tamazulapam", State: "MX-OAX"}},
	640: {{Code: 640, Name: "Zimatlán", State: "MX-OAX"}},
	650: {{Code: 650, Name: "Cuautlancingo", State: "MX-PUE"}},
	651: {{Code: 651, Name: "Acatlan", State: "MX-PUE"}},
	652: {{Code: 652, Name: "Acatzingo", State: "MX-PUE"}},
	653: {{Code: 653, Name: "Amozoc", State: "MX-PUE"}},
	654: {{Code: 654, Name: "Atlixco", State: "MX-PUE"}},
	655: {{Code: 655, Name: "Ciudad Serdan", State: "MX-PUE"}},
	656: {{Code: 656, Name: "Cuetzalan", State: "MX-PUE"}},
	657: {{Code: 657, Name: "Chiautla", State: "MX-PUE"}},
	658: {{Code: 658, Name: "Chignahuapan", State: "MX-PUE"}},
	659: {{Code: 659, Name: "Huauchinango", State: "MX-PUE"}},
	660: {{Code: 660, Name: "Huejotzingo", State: "MX-PUE"}},
	661: {{Code: 661, Name: "Hueytamalco", State: "MX-PUE"}},
	662: {{Code: 662, Name: "Izúcar de Matamoros", State: "MX-PUE"}},
	663: {{Code: 663, Name: "Libres", State: "MX-PUE"}},
	664: {{Code: 664, Name: "Nealtican", State: "MX-PUE"}},
	665: {{Code: 665, Name: "Nvo Necaxa", State: "MX-PUE"}},
	666: {{Code: 666, Name: "Rafael Lara Grajales", State: "MX-PUE"}},
	667: {{Code: 667, Name: "San Martín Texmelucan", State: "MX-PUE"}},
	668: {{Code: 668, Name: "Sto Tomas Hueyotlipan", State: "MX-PUE"}},
	669: {{Code: 669, Name: "Tecamachalco", State: "MX-PUE"}},
	670: {{Code: 670, Name: "Tehuacán", State: "MX-PUE"}},
	671: {{Code: 671, Name: "Tepeaca", State: "MX-PUE"}},
	672: {{Code: 672, Name: "Teziutlán", State: "MX-PUE"}},
	673: {{Code: 673, Name: "Tlatlauquitepec", State: "MX-PUE"}},
	674: {{Code: 674, Name: "Xicotepec de Juárez", State: "MX-PUE"}},
	675: {{Code: 675, Name: "Zacapoaxtla", State: "MX-PUE"}},
	676: {{Code: 676, Name: "Zacatlán", State: "MX-PUE"}},
	680: {{Code: 680, Name: "El Pueblito Correg.", State: "MX-QUE"}},
	681: {{Code: 681, Name: "Amealco", State: "MX-QUE"}},
	682: {{Code: 682, Name: "Cadereyta", State: "MX-QUE"}},
	683: {{Code: 683, Name: "Ezequiel Montes", State: "MX-QUE"}},
	684: {{Code: 684, Name: "Jalpan", State: "MX-QUE"}},
	685: {{Code: 685, Name: "San Juan del Río", State: "MX-QUE"}},
	686: {{Code: 686, Name: "Tequisquiapan", State: "MX-QUE"}},
	690: {{Code: 690, Name: "Chetumal", State: "MX-ROO"}},
	691: {{Code: 691, Name: "Cancún", State: "MX-ROO"}},
	692: {{Code: 692, Name: "Cozumel", State: "MX-ROO"}},
	693: {{Code: 693, Name: "Isla Mujeres", State: "MX-ROO"}},
	694: {{Code: 694, Name: "Playa del Carmen", State: "MX-ROO"}},
	700: {{Code: 700, Name: "San Luis Potosí", State: "MX-SLP"}},
	701: {{Code: 701, Name: "Axtla de Terrazas", State: "MX-SLP"}},
	702: {{Code: 702, Name: "Cardenas", State: "MX-SLP"}},
	703: {{Code: 703, Name: "Cerritos", State: "MX-SLP"}},
	704: {{Code: 704, Name: "Ciudad del Maiz", State: "MX-SLP"}},
	705: {{Code: 705, Name: "Ciudad Valles", State: "MX-SLP"}},
	706: {{Code: 706, Name: "Charcas", State: "MX-SLP"}},
	707: {{Code: 707, Name: "Ebano", State: "MX-SLP"}},
	708: {{Code: 708, Name: "Guadalcazar", State: "MX-SLP"}},
	709: {{Code: 709, Name: "Matehuala", State: "MX-SLP"}},
	710: {{Code: 710, Name: "Rayon", State: "MX-SLP"}},
	711: {{Code: 711, Name: "Río Verde", State: "MX-SLP"}},
	712: {{Code: 712, Name: "Salinas de Hidalgo", State: "MX-SLP"}},
	713: {{Code: 713, Name: "Santa Maria del Rio", State: "MX-SLP"}},
	714: {{Code: 714, Name: "Tamasopo", State: "MX-SLP"}},
	715: {{Code: 715, Name: "Tamazunchale", State: "MX-SLP"}},
	716: {{Code: 716, Name: "Tamuín", State: "MX-SLP"}},
	717: {{Code: 717, Name: "Tancanhuitz de Santos", State: "MX-SLP"}},
	718: {{Code: 718, Name: "Tanquian", State: "MX-SLP"}},
	719: {{Code: 719, Name: "Tierra Nueva", State: "MX-SLP"}},
	720: {{Code: 720, Name: "Venado", State: "MX-SLP"}},
	721: {{Code: 721, Name: "Xilitla", State: "MX-SLP"}},
	722: {{Code: 722, Name: "Villa de Arista", State: "MX-SLP"}},
	730: {{Code: 730, Name: "Culiacán", State: "MX-SIN"}},
	731: {{Code: 731, Name: "Ahome", State: "MX-SIN"}},
	732: {{Code: 732, Name: "Angostura", State: "MX-SIN"}},
	733: {{Code: 733, Name: "Badiraguato", State: "MX-SIN"}},
	734: {{Code: 734, Name: "Bamoa", State: "MX-SIN"}},
	735: {{Code: 735, Name: "Concordia", State: "MX-SIN"}},
	736: {{Code: 736, Name: "Cosala", State: "MX-SIN"}},
	737: {{Code: 737, Name: "Choix", State: "MX-SIN"}},
	738: {{Code: 738, Name: "El Fuerte", State: "MX-SIN"}},
	739: {{Code: 739, Name: "Escuinapa de Hidalgo", State: "MX-SIN"}},
	740: {{Code: 740, Name: "Guamúchil", State: "MX-SIN"}},
	741: {{Code: 741, Name: "Guasave", State: "MX-SIN"}},
	742: {{Code: 742, Name: "La Cruz de Elota", State: "MX-SIN"}},
	743: {{Code: 743, Name: "Los Mochis", State: "MX-SIN"}},
	744: {{Code: 744, Name: "Mazatlán", State: "MX-SIN"}},
	745: {{Code: 745, Name: "Mocorito", State: "MX-SIN"}},
	746: {{Code: 746, Name: "Navolato", State: "MX-SIN"}},
	747: {{Code: 747, Name: "Quila", State: "MX-SIN"}},
	748: {{Code: 748, Name: "Rosario", State: "MX-SIN"}},
	749: {{Code: 749, Name: "San Blas", State: "MX-SIN"}},
	750: {{Code: 750, Name: "San Ignacio", State: "MX-SIN"}},
	760: {{Code: 760, Name: "Hermosillo", State: "MX-SON"}},
	761: {{Code: 761, Name: "Agua Prieta", State: "MX-SON"}},
	762: {{Code: 762, Name: "Alamos", State: "MX-SON"}},
	763: {{Code: 763, Name: "Altar", State: "MX-SON"}},
	764: {{Code: 764, Name: "Baviacora", State: "MX-SON"}},
	765: {{Code: 765, Name: "Caborca", State: "MX-SON"}},
	766: {{Code: 766, Name: "Cananea", State: "MX-SON"}},
	767: {{Code: 767, Name: "Ciudad Obregón", State: "MX-SON"}},
	768: {{Code: 768, Name: "Cumpas", State: "MX-SON"}},
	769: {{Code: 769, Name: "Empalme", State: "MX-SON"}},
	770: {{Code: 770, Name: "Guaymas", State: "MX-SON"}},
	771: {{Code: 771, Name: "Huatabampo", State: "MX-SON"}},
	772: {{Code: 772, Name: "Luis B. Sanchez", State: "MX-SON"}},
	773: {{Code: 773, Name: "Magdalena de Kino", State: "MX-SON"}},
	774: {{Code: 774, Name: "Miguel Aleman", State: "MX-SON"}},
	775: {{Code: 775, Name: "Moctezuma", State: "MX-SON"}},
	776: {{Code: 776, Name: "Nacozari de García", State: "MX-SON"}},
	777: {{Code: 777, Name: "Navojoa", State: "MX-SON"}},
	778: {{Code: 778, Name: "Nogales", State: "MX-SON"}},
	779: {{Code: 779, Name: "Puerto Peñasco", State: "MX-SON"}},
	780: {{Code: 780, Name: "San Luis Río Colorado", State: "MX-SON"}},
	781: {{Code: 781, Name: "Santa Ana", State: "MX-SON"}},
	782: {{Code: 782, Name: "Ures", State: "MX-SON"}},
	783: {{Code: 783, Name: "Villa Juarez (Irrigacion)", State: "MX-SON"}},
	790: {{Code: 790, Name: "Villa Hermosa", State: "MX-TAB"}},
	791: {{Code: 791, Name: "Balancan", State: "MX-TAB"}},
	792: {{Code: 792, Name: "Cardenas", State: "MX-TAB"}},
	793: {{Code: 793, Name: "Ciudad Pemex", State: "MX-TAB"}},
	794: {{Code: 794, Name: "Comalcalco", State: "MX-TAB"}},
	795: {{Code: 795, Name: "Cunduacan", State: "MX-TAB"}},
	796: {{Code: 796, Name: "Emiliano Zapata", State: "MX-TAB"}},
	797: {{Code: 797, Name: "Frontera", State: "MX-TAB"}},
	798: {{Code: 798, Name: "Huimanguillo", State: "MX-TAB"}},
	799: {{Code: 799, Name: "Jalapa", State: "MX-TAB"}},
	800: {{Code: 800, Name: "Jalpa de Méndez", State: "MX-TAB"}},
	801: {{Code: 801, Name: "Jonuta", State: "MX-TAB"}},
	802: {{Code: 802, Name: "Macuspana", State: "MX-TAB"}},
	803: {{Code: 803, Name: "Nacajuca", State: "MX-TAB"}},
	804: {{Code: 804, Name: "Paraíso", State: "MX-TAB"}},
	805: {{Code: 805, Name: "Tacotalpa", State: "MX-TAB"}},
	806: {{Code: 806, Name: "Teapa", State: "MX-TAB"}},
	807: {{Code: 807, Name: "Tenosique", State: "MX-TAB"}},
	810: {{Code: 810, Name: "Ciudad Victoria", State: "MX-TAM"}},
	811: {{Code: 811, Name: "Altamira", State: "MX-TAM"}},
	812: {{Code: 812, Name: "Camargo", State: "MX-TAM"}},
	813: {{Code: 813, Name: "Ciudad Madero", State: "MX-TAM"}},
	814: {{Code: 814, Name: "Ciudad Mante", State: "MX-TAM"}},
	815: {{Code: 815, Name: "Ciudad Miguel Aleman", State: "MX-TAM"}},
	816: {{Code: 816, Name: "Gonzalez", State: "MX-TAM"}},
	817: {{Code: 817, Name: "Gustavo Diaz Ordaz", State: "MX-TAM"}},
	818: {{Code: 818, Name: "Matamoros", State: "MX-TAM"}},
	819: {{Code: 819, Name: "Mier", State: "MX-TAM"}},
	820: {{Code: 820, Name: "Nva Ciudad Guerrero", State: "MX-TAM"}},
	821: {{Code: 821, Name: "Nuevo Laredo", State: "MX-TAM"}},
	822: {{Code: 822, Name: "Hidalgo", State: "MX-TAM"}},
	823: {{Code: 823, Name: "Río Bravo", State: "MX-TAM"}},
	824: {{Code: 824, Name: "San Fernando", State: "MX-TAM"}},
	825: {{Code: 825, Name: "Soto la Marina", State: "MX-TAM"}},
	826: {{Code: 826, Name: "Valle Hermoso", State: "MX-TAM"}},
	827: {{Code: 827, Name: "Xicotencatl", State: "MX-TAM"}},
	830: {{Code: 830, Name: "Tlaxcala", State: "MX-TLA"}},
	831: {{Code: 831, Name: "Amaxac de Guerrero", State: "MX-TLA"}},
	832: {{Code: 832, Name: "Apizaco", State: "MX-TLA"}},
	833: {{Code: 833, Name: "Calpulalpan", State: "MX-TLA"}},
	834: {{Code: 834, Name: "Chiautempan", State: "MX-TLA"}},
	835: {{Code: 835, Name: "Huamantla", State: "MX-TLA"}},
	836: {{Code: 836, Name: "Papalotla", State: "MX-TLA"}},
	837: {{Code: 837, Name: "Santa Maria Nativitas", State: "MX-TLA"}},
	838: {{Code: 838, Name: "Tlaxco", State: "MX-TLA"}},
	839: {{Code: 839, Name: "Zacatelco", State: "MX-TLA"}},
	840: {{Code: 840, Name: "Xalapa", State: "MX-VER"}},
	841: {{Code: 841, Name: "Acayucan", State: "MX-VER"}},
	842: {{Code: 842, Name: "Adalberto Tejeda", State: "MX-VER"}},
	843: {{Code: 843, Name: "Agua Dulce", State: "MX-VER"}},
	844: {{Code: 844, Name: "Agua Dulce (Papantla)", State: "MX-VER"}},
	845: {{Code: 845, Name: "Álamo", State: "MX-VER"}},
	846: {{Code: 846, Name: "Altotonga", State: "MX-VER"}},
	847: {{Code: 847, Name: "Alvarado", State: "MX-VER"}},
	848: {{Code: 848, Name: "Banderilla", State: "MX-VER"}},
	849: {{Code: 849, Name: "Boca del Río", State: "MX-VER"}},
	850: {{Code: 850, Name: "Catemaco", State: "MX-VER"}},
	851: {{Code: 851, Name: "Cerro Azul", State: "MX-VER"}},
	852: {{Code: 852, Name: "Ciudad Mendoza", State: "MX-VER"}},
	853: {{Code: 853, Name: "Coatepec", State: "MX-VER"}},
	854: {{Code: 854, Name: "Coatzacoalcos", State: "MX-VER"}},
	855: {{Code: 855, Name: "Córdoba", State: "MX-VER"}},
	856: {{Code: 856, Name: "Cosamaloapan", State: "MX-VER"}},
	858: {{Code: 858, Name: "Coscomatepec", State: "MX-VER"}},
	859: {{Code: 859, Name: "Cosoleacaque", State: "MX-VER"}},
	860: {{Code: 860, Name: "Cuitláhuac", State: "MX-VER"}},
	861: {{Code: 861, Name: "Chicontepec", State: "MX-VER"}},
	862: {{Code: 862, Name: "El Naranjal", State: "MX-VER"}},
	863: {{Code: 863, Name: "Fortín de las Flores", State: "MX-VER"}},
	864: {{Code: 864, Name: "Gutiérrez Zamora", State: "MX-VER"}},
	865: {{Code: 865, Name: "Huatusco", State: "MX-VER"}},
	866: {{Code: 866, Name: "Hueyapan de Ocampo", State: "MX-VER"}},
	867: {{Code: 867, Name: "Isla", State: "MX-VER"}},
	868: {{Code: 868, Name: "Ixtaczoquitlán", State: "MX-VER"}},
	869: {{Code: 869, Name: "Jáltipan de Morelos", State: "MX-VER"}},
	870: {{Code: 870, Name: "Jesus Carranza", State: "MX-VER"}},
	871: {{Code: 871, Name: "Juan Rodríguez Clara", State: "MX-VER"}},
	872: {{Code: 872, Name: "La Antigua", State: "MX-VER"}},
	873: {{Code: 873, Name: "Las Choapas", State: "MX-VER"}},
	874: {{Code: 874, Name: "Lerdo de Tejada", State: "MX-VER"}},
	875: {{Code: 875, Name: "Los Naranjos", State: "MX-VER"}},
	876: {{Code: 876, Name: "Martínez de la Torre", State: "MX-VER"}},
	877: {{Code: 877, Name: "Minatitlán", State: "MX-VER"}},
	878: {{Code: 878, Name: "Misantla", State: "MX-VER"}},
	879: {{Code: 879, Name: "Nanchital", State: "MX-VER"}},
	880: {{Code: 880, Name: "Naolinco", State: "MX-VER"}},
	881: {{Code: 881, Name: "Naranjos", State: "MX-VER"}},
	882: {{Code: 882, Name: "Orizaba", State: "MX-VER"}},
	883: {{Code: 883, Name: "Ozuluama", State: "MX-VER"}},
	884: {{Code: 884, Name: "Panuco", State: "MX-VER"}},
	885: {{Code: 885, Name: "Papantla", State: "MX-VER"}},
	886: {{Code: 886, Name: "Perote", State: "MX-VER"}},
	887: {{Code: 887, Name: "Playa Vicente", State: "MX-VER"}},
	888: {{Code: 888, Name: "Poza Rica", State: "MX-VER"}},
	889: {{Code: 889, Name: "Río Blanco", State: "MX-VER"}},
	890: {{Code: 890, Name: "San Andrés Tuxtla", State: "MX-VER"}},
	891: {{Code: 891, Name: "San Rafael", State: "MX-VER"}},
	892: {{Code: 892, Name: "Soledad de Doblado", State: "MX-VER"}},
	893: {{Code: 893, Name: "Tamiahua", State: "MX-VER"}},
	894: {{Code: 894, Name: "Tantoyuca", State: "MX-VER"}},
	895: {{Code: 895, Name: "Tempoal de Sanchez", State: "MX-VER"}},
	896: {{Code: 896, Name: "Teocelo", State: "MX-VER"}},
	897: {{Code: 897, Name: "Tezonapa", State: "MX-VER"}},
	898: {{Code: 898, Name: "Tierra Blanca", State: "MX-VER"}},
	899: {{Code: 899, Name: "Tihuatlan", State: "MX-VER"}},
	900: {{Code: 900, Name: "Tlacotalpan", State: "MX-VER"}},
	901: {{Code: 901, Name: "Tlapacoyan", State: "MX-VER"}},
	902: {{Code: 902, Name: "Tres Valles", State: "MX-VER"}},
	903: {{Code: 903, Name: "Tuxpan", State: "MX-VER"}},
	904: {{Code: 904, Name: "Vega de Alatorre", State: "MX-VER"}},
	905: {{Code: 905, Name: "Veracruz", State: "MX-VER"}},
	906: {{Code: 906, Name: "Xico", State: "MX-VER"}},
	910: {{Code: 910, Name: "Mérida", State: "MX-YUC"}},
	911: {{Code: 911, Name: "Izamal", State: "MX-YUC"}},
	912: {{Code: 912, Name: "Maxcanu", State: "MX-YUC"}},
	913: {{Code: 913, Name: "Motul", State: "MX-YUC"}},
	914: {{Code: 914, Name: "Oxkutzcab", State: "MX-YUC"}},
	915: {{Code: 915, Name: "Puerto Progreso", State: "MX-YUC"}},
	916: {{Code: 916, Name: "Tekax", State: "MX-YUC"}},
	917: {{Code: 917, Name: "Ticul", State: "MX-YUC"}},
	918: {{Code: 918, Name: "Tizimín", State: "MX-YUC"}},
	919: {{Code: 919, Name: "Uman", State: "MX-YUC"}},
	920: {{Code: 920, Name: "Valladolid", State: "MX-YUC"}},
	930: {{Code: 930, Name: "Zacatecas", State: "MX-ZAC"}},
	931: {{Code: 931, Name: "Apozol", State: "MX-ZAC"}},
	932: {{Code: 932, Name: "Concepcion del Oro", State: "MX-ZAC"}},
	933: {{Code: 933, Name: "Fresnillo", State: "MX-ZAC"}},
	934: {{Code: 934, Name: "Guadalupe", State: "MX-ZAC"}},
	935: {{Code: 935, Name: "Jalpa", State: "MX-ZAC"}},
	936: {{Code: 936, Name: "Jerez de Garcia Salinas", State: "MX-ZAC"}},
	937: {{Code: 937, Name: "Juan Aldama", State: "MX-ZAC"}},
	938: {{Code: 938, Name: "Juchipila", State: "MX-ZAC"}},
	939: {{Code: 939, Name: "Loreto", State: "MX-ZAC"}},
	940: {{Code: 940, Name: "Luis Moya", State: "MX-ZAC"}},
	941: {{Code: 941, Name: "Miguel Auza", State: "MX-ZAC"}},
	942: {{Code: 942, Name: "Monte Escobedo", State: "MX-ZAC"}},
	943: {{Code: 943, Name: "Morelos", State: "MX-ZAC"}},
	944: {{Code: 944, Name: "Moyahua de Estrada", State: "MX-ZAC"}},
	945: {{Code: 945, Name: "Nieves", State: "MX-ZAC"}},
	946: {{Code: 946, Name: "Nochistlán de Mejia", State: "MX-ZAC"}},
	947: {{Code: 947, Name: "Ojocaliente", State: "MX-ZAC"}},
	948: {{Code: 948, Name: "Pinos", State: "MX-ZAC"}},
	949: {{Code: 949, Name: "Rio Grande", State: "MX-ZAC"}},
	950: {{Code: 950, Name: "Sain Alto", State: "MX-ZAC"}},
	951: {{Code: 951, Name: "San Pedro Apulco", State: "MX-ZAC"}},
	952: {{Code: 952, Name: "Sombrerete", State: "MX-ZAC"}},
	953: {{Code: 953, Name: "Tabasco", State: "MX-ZAC"}},
	954: {{Code: 954, Name: "Tepechitlan", State: "MX-ZAC"}},
	955: {{Code: 955, Name: "Tepetongo", State: "MX-ZAC"}},
	956: {{Code: 956, Name: "Teul de Glez. Ortega", State: "MX-ZAC"}},
	957: {{Code: 957, Name: "Cosautlan", State: "MX-VER"}},
	958: {{Code: 958, Name: "Valparaíso", State: "MX-ZAC"}},
	959: {{Code: 959, Name: "Valla de Cos", State: "MX-ZAC"}},
	960: {{Code: 960, Name: "Victor Rosales", State: "MX-ZAC"}},
	961: {{Code: 961, Name: "Villa Gonzalez Ortega", State: "MX-ZAC"}},
	962: {{Code: 962, Name: "Villanueva", State: "MX-ZAC"}},
	969: {{Code: 969, Name: "Ciudad de México", State: "MX-CMX"}},
}

func ReturnRandomCity() (ClabeCityInfo, int) {
	mapLen := len(citiesMap)
	randNumber, err := rand.Int(rand.Reader, big.NewInt(int64(mapLen-1)))
	if err != nil {
		log.Println(err)
	}
	intRandomNumber := int(randNumber.Int64())
	randomCity := citiesMap[intRandomNumber]
	return randomCity[0], intRandomNumber
}
